using Microsoft.CodeAnalysis;

using System.Linq;

namespace Bannerlord.UIExtenderEx.Analyzers;

/// <summary>
/// Gives a mod <c>[assembly: PrefabLink]</c> when the UIExtenderEx it references has none. The attribute is read only by
/// the analyzers, so it can come with them: an internal copy, <c>[Conditional]</c> so that no use of it is written into
/// the mod's assembly. A UIExtenderEx that declares it (3.0 and later) or a mod that declares it itself gets nothing.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class PrefabLinkAttributeGenerator : IIncrementalGenerator
{
    public const string MetadataName = "Bannerlord.UIExtenderEx.Attributes.PrefabLinkAttribute";

    public const string HintName = "Bannerlord.UIExtenderEx.Attributes.PrefabLinkAttribute.g.cs";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var needed = context.CompilationProvider.Select(static (compilation, _) => IsNeeded(compilation));
        context.RegisterSourceOutput(needed, static (output, isNeeded) =>
        {
            if (isNeeded)
                output.AddSource(HintName, Source);
        });
    }

    private static bool IsNeeded(Compilation compilation)
    {
        // Nothing to link without UIExtenderEx; the mod's own declaration wins
        if (compilation.Assembly.GetTypeByMetadataName(MetadataName) is not null)
            return false;
        var mixinAttribute = compilation.GetTypesByMetadataName("Bannerlord.UIExtenderEx.Attributes.ViewModelMixinAttribute");
        if (!mixinAttribute.Any(IsUIExtenderEx))
            return false;
        return !compilation.GetTypesByMetadataName(MetadataName).Any(t => IsUIExtenderEx(t) && t.DeclaredAccessibility == Accessibility.Public);
    }

    private static bool IsUIExtenderEx(INamedTypeSymbol type) => type.ContainingAssembly.Name == "Bannerlord.UIExtenderEx";

    // C# 7.3, which a mod targeting .NET Framework compiles with unless it says otherwise: no nullable annotations
    private const string Source = """
        // <auto-generated>
        // Bannerlord.UIExtenderEx.Analyzers: [assembly: PrefabLink] for a UIExtenderEx that has none. Read by the analyzers
        // only; no use of it is compiled into the assembly.
        // </auto-generated>

        namespace Bannerlord.UIExtenderEx.Attributes
        {
            /// <summary>
            /// Links a prefab patch, or a prefab of the mod's own, to the ViewModel its XML binds and, optionally, to the mixin
            /// whose members it binds. Read by Bannerlord.UIExtenderEx.Analyzers, which checks the XML against the ViewModel and
            /// its mixins and the three against each other; UIExtenderEx itself does not read it.
            /// </summary>
            [global::System.AttributeUsage(global::System.AttributeTargets.Assembly, AllowMultiple = true)]
            [global::System.Diagnostics.Conditional("BANNERLORD_UIEXTENDEREX_ANALYZERS")]
            internal sealed class PrefabLinkAttribute : global::System.Attribute
            {
                /// <summary>The prefab patch: a class marked PrefabExtension. Null when Prefab is set.</summary>
                public global::System.Type Patch { get; }

                /// <summary>The prefab of the mod: the name it is registered under, or its file name without the extension. Null when Patch is set.</summary>
                public string Prefab { get; }

                /// <summary>The ViewModel the XML binds where it goes in.</summary>
                public global::System.Type ViewModel { get; }

                /// <summary>The mixin whose members the XML binds (optional).</summary>
                public global::System.Type Mixin { get; }

                /// <summary>Links a prefab patch to the ViewModel at the node it goes into.</summary>
                public PrefabLinkAttribute(global::System.Type patch, global::System.Type viewModel)
                {
                    Patch = patch;
                    ViewModel = viewModel;
                }

                /// <summary>Links a prefab patch to the ViewModel at the node it goes into and to the mixin whose members it binds.</summary>
                public PrefabLinkAttribute(global::System.Type patch, global::System.Type viewModel, global::System.Type mixin)
                {
                    Patch = patch;
                    ViewModel = viewModel;
                    Mixin = mixin;
                }

                /// <summary>Links a prefab of the mod to the ViewModel at its root.</summary>
                public PrefabLinkAttribute(string prefab, global::System.Type viewModel)
                {
                    Prefab = prefab;
                    ViewModel = viewModel;
                }

                /// <summary>Links a prefab of the mod to the ViewModel at its root and to the mixin whose members it binds.</summary>
                public PrefabLinkAttribute(string prefab, global::System.Type viewModel, global::System.Type mixin)
                {
                    Prefab = prefab;
                    ViewModel = viewModel;
                    Mixin = mixin;
                }
            }
        }

        """;
}
