using Bannerlord.UIExtenderEx.CompiledPrefabs.Compilation;
using Bannerlord.UIExtenderEx.GauntletUI.CodeGenerator;

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

using TaleWorlds.GauntletUI.PrefabSystem;
using TaleWorlds.Library;
using TaleWorlds.Library.CodeGeneration;

namespace Bannerlord.UIExtenderEx.CompiledPrefabs;

/// <summary>
/// Manages the compilation, caching, and registration of dynamic C# prefab variants generated from patched XML prefab trees.
/// </summary>
/// <remarks>
/// <para>
/// Replaces TaleWorlds pre-compiled widget variants in <see cref="GeneratedPrefabContext"/> with assemblies compiled from patched XML.
/// For (movie, ViewModel) pairs whose prefab hierarchy incorporates modified XML nodes, generates C# source via the forked code generator,
/// compiles assemblies on a background worker thread, persists binaries to the disk cache, and registers new factory creators over the base game registrations.
/// During background compilation, the movie falls back to standard XML instantiation without UI stalls.
/// </para>
/// <para>
/// All coordinator methods execute on the main thread alongside the TaleWorlds Gauntlet UI system; compilation and cache I/O run asynchronously.
/// </para>
/// </remarks>
public sealed class CompiledPrefabManager
{
    public const string GeneratedNamespace = "Bannerlord.UIExtenderEx.AutoGenerated";

    private readonly record struct PrefabKey(string Movie, string Variant);

    /// <summary>Represents an active in-memory compiled prefab registration containing fingerprint, dependencies, and creator callback.</summary>
    private sealed record RegisteredPrefab(string Fingerprint, IReadOnlyList<string> Dependencies, Action<GeneratedPrefabContext> Collect);

    private sealed record CompileJobResult(PrefabKey Key, string Fingerprint, IReadOnlyList<string> Dependencies, Assembly? Assembly, IReadOnlyList<string> Errors, string? FailureDirectory);

    private readonly ICompiledPrefabEnvironment _environment;
    private readonly Dictionary<PrefabKey, RegisteredPrefab> _registered = new();
    private readonly HashSet<PrefabKey> _pending = [];
    /// <summary>
    /// Tracks failed compilation attempts alongside the <see cref="UIEnvironmentVersion"/> in which the failure occurred.
    /// </summary>
    private readonly Dictionary<(PrefabKey Key, string Fingerprint), int> _failed = new();
    /// <summary>Tracks failure notifications presented to the user, preventing repeated modal warnings for identical failures.</summary>
    private readonly HashSet<(PrefabKey Key, string Fingerprint)> _warned = [];
    private readonly HashSet<string> _unreadableReferences = new(StringComparer.OrdinalIgnoreCase);
    private readonly ConcurrentQueue<CompileJobResult> _finished = new();
    /// <summary>A cached build and its one load into the process, shared by the preload and the main thread.</summary>
    private sealed record CachedLoad(PrefabCacheEntry Entry, Lazy<Assembly> Assembly);

    /// <summary>
    /// Cached builds loaded or being loaded, keyed by <see cref="PrefabCacheEntry.Key"/>. A build is loaded at most once:
    /// a movie asking for one the preload is still loading waits for it instead of loading a second copy.
    /// </summary>
    private readonly ConcurrentDictionary<string, CachedLoad> _cachedLoads = new(StringComparer.Ordinal);
    private bool _deferredPreloaded;
    private readonly object _cacheLock = new();
    private bool _cacheChecked;
    private PrefabCache? _cache;
    private readonly DateTime _sessionStart = DateTime.UtcNow;
    private readonly object _timingsLock = new();
    private PrefabTimings? _timings;

    public CompiledPrefabManager(ICompiledPrefabEnvironment environment)
    {
        _environment = environment;
    }

    /// <summary>Gets a value indicating whether the manager encountered a fatal exception and is disabled for the remainder of the session.</summary>
    public bool IsDisabled { get; private set; }

    /// <summary>
    /// Creates a new <see cref="CompiledPrefabManager"/> using the specified environment factory.
    /// </summary>
    /// <param name="environmentFactory">A factory creating the compilation environment.</param>
    /// <returns>A configured <see cref="CompiledPrefabManager"/>, or a disabled instance if environment creation fails.</returns>
    /// <remarks>
    /// Catches initialization exceptions and falls back to a disabled environment to prevent TypeInitializationException errors during UI loading.
    /// </remarks>
    public static CompiledPrefabManager Create(Func<ICompiledPrefabEnvironment> environmentFactory)
    {
        try
        {
            return new(environmentFactory());
        }
        catch (Exception e)
        {
            Trace.TraceError("UIExtenderEx: compiled prefabs could not be set up, using XML prefabs: {0}", e);
            return new(new DisabledCompiledPrefabEnvironment()) { IsDisabled = true };
        }
    }

    private bool _warmedUp;

    /// <summary>
    /// Warms up background compilers and preloads cached assemblies during initial module loading to eliminate UI stall on first movie instantiation.
    /// </summary>
    /// <remarks>
    /// Invoked during <c>SubModule.OnSubModuleLoad</c>. Idempotent.
    /// </remarks>
    public void WarmUpCompilers()
    {
        if (IsDisabled || _warmedUp || !_environment.IsEnabled)
            return;
        WarmUpCompilersCore();
    }

    /// <remarks>
    /// Out-of-line method implementation preventing JIT compilation of Roslyn compiler dependencies when the manager is disabled.
    /// </remarks>
    [MethodImpl(MethodImplOptions.NoInlining)]
    private void WarmUpCompilersCore()
    {
        _warmedUp = true;

        try
        {
            // Collects initial reference paths on the main thread where mixin registrations are valid.
            var references = PrefabReferenceSet.CollectPaths(null, null);
            _environment.RunInBackground(() =>
            {
                PreloadCache("while the modules load");
                WarmUpGenerator();

                var stopwatch = Stopwatch.StartNew();
                var compiler = _environment.Compiler;

                try
                {
                    compiler.WarmUp(references);
                    Trace.TraceInformation("UIExtenderEx: warmed up {0} in {1} ms", compiler.Name, stopwatch.ElapsedMilliseconds);
                    RecordTiming("warm-up compiler", null, null, stopwatch, compiler.Name);
                }
                catch (Exception e)
                {
                    Trace.TraceWarning("UIExtenderEx: warming up {0} failed, the first compilation will be slower: {1}", compiler.Name, e.Message);
                    RecordTiming("warm-up compiler", null, null, stopwatch, $"{compiler.Name} failed: {e.Message}");
                }
            });
        }
        catch (Exception e)
        {
            Trace.TraceWarning("UIExtenderEx: compiler warm-up could not be scheduled: {0}", e.Message);
        }
    }

    /// <summary>
    /// Preloads the cached builds the start-up preload had to leave out because an assembly they reference was not loaded yet.
    /// </summary>
    /// <remarks>
    /// Invoked during <c>SubModule.OnBeforeInitialModuleScreenSetAsRoot</c>, when module loaders have loaded their game
    /// implementations (MCM's, for one). A build whose references are still not loaded (a disabled module's) is never preloaded;
    /// the movie that asks for it checks it and loads it then, or compiles it again. Idempotent.
    /// </remarks>
    public void PreloadDeferredBuilds()
    {
        if (IsDisabled || _deferredPreloaded || !_environment.IsEnabled)
            return;
        _deferredPreloaded = true;

        try
        {
            _environment.RunInBackground(() => PreloadCache("once the modules have loaded"));
        }
        catch (Exception e)
        {
            Trace.TraceWarning("UIExtenderEx: the preload of the remaining cached prefabs could not be scheduled: {0}", e.Message);
        }
    }

    /// <summary>
    /// Pre-JITs code generator methods on a background thread to prevent JIT compilation latency during the first movie load.
    /// </summary>
    /// <remarks>
    /// Invokes <see cref="RuntimeHelpers.PrepareMethod"/> across code generator types without instantiating game objects or touching UI state.
    /// </remarks>
    private void WarmUpGenerator()
    {
        var stopwatch = Stopwatch.StartNew();
        var prepared = 0;
        try
        {
            foreach (var type in GeneratorTypes())
            {
                if (type.ContainsGenericParameters)
                    continue;

                foreach (var method in type.GetMethods(GeneratorMembers).Cast<MethodBase>().Concat(type.GetConstructors(GeneratorMembers)))
                {
                    if (method.IsAbstract || method.ContainsGenericParameters || method.DeclaringType != type)
                        continue;

                    try
                    {
                        RuntimeHelpers.PrepareMethod(method.MethodHandle);
                        prepared++;
                    }
                    catch (Exception)
                    {
                        // Ignores methods that fail JIT preparation, leaving them to compile on first invocation.
                    }
                }
            }
            Trace.TraceInformation("UIExtenderEx: warmed up the code generator, {0} methods in {1} ms", prepared, stopwatch.ElapsedMilliseconds);
            RecordTiming("warm-up generator", null, null, stopwatch, $"{prepared} methods");
        }
        catch (Exception e)
        {
            Trace.TraceWarning("UIExtenderEx: warming up the code generator failed, the first movie will be slower: {0}", e.Message);
        }
    }

    private const BindingFlags GeneratorMembers =
        BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly;

    /// <summary>
    /// Enumerates code generator and code emission types across the generator fork and TaleWorlds library.
    /// </summary>
    private static IEnumerable<Type> GeneratorTypes()
    {
        var fork = typeof(PrefabCodeGenerator);
        var library = typeof(ClassCode);
        return fork.Assembly.GetTypes().Where(x => x.Namespace == fork.Namespace)
            .Concat(library.Assembly.GetTypes().Where(x => x.Namespace == library.Namespace));
    }

    /// <summary>
    /// Evaluates whether a compiled variant exists or can be initiated for the specified movie and ViewModel data source.
    /// </summary>
    /// <param name="widgetFactory">The widget factory resolving prefabs and widgets.</param>
    /// <param name="movieName">The root movie name requested by Gauntlet.</param>
    /// <param name="dataSource">The ViewModel data source bound to the movie.</param>
    /// <returns><see langword="true"/> if an up-to-date compiled variant is registered in <see cref="GeneratedPrefabContext"/>; otherwise, <see langword="false"/>.</returns>
    public bool TryUseCompiledPrefab(WidgetFactory widgetFactory, string movieName, IViewModel? dataSource)
    {
        if (IsDisabled || dataSource is null || !_environment.IsEnabled)
            return false;
        return TryUseCompiledPrefabCore(widgetFactory, movieName, dataSource);
    }

    /// <remarks>Out-of-line method implementation preventing premature JIT compilation of compiler types.</remarks>
    [MethodImpl(MethodImplOptions.NoInlining)]
    private bool TryUseCompiledPrefabCore(WidgetFactory widgetFactory, string movieName, IViewModel dataSource)
    {
        // Executes synchronously on the main thread during movie loading; timing logs record duration of each evaluation phase.
        var stopwatch = Stopwatch.StartNew();
        void Report(string outcome)
        {
            Trace.TraceInformation("UIExtenderEx: prefab '{0}': {1} ms on the main thread, {2}", movieName, stopwatch.ElapsedMilliseconds, outcome);
            RecordTiming("decide", movieName, dataSource.GetType().FullName, stopwatch, outcome);
        }

        try
        {
            var context = widgetFactory.GeneratedPrefabContext;
            DrainFinished(context);

            var viewModelType = dataSource.GetType();
            var key = new PrefabKey(movieName, viewModelType.FullName ?? viewModelType.Name);
            // Evaluates fast cache lookup against current factory state and cached sections before creating a pinned snapshot.
            var fingerprint = _environment.ComputeFingerprint(widgetFactory, movieName, viewModelType, out var failure);
            var fingerprintMilliseconds = stopwatch.ElapsedMilliseconds;
            if (fingerprint is null)
            {
                Report($"no fingerprint ({failure ?? "a prefab of the movie has no recorded XML"}), XML");
                return false;
            }

            if (TryUseExisting(context, key, movieName, viewModelType, fingerprint, out var outcome) is { } decided)
            {
                Report($"fingerprint {fingerprintMilliseconds} ms, {outcome}");
                return decided;
            }

            // Pins the parsed prefab tree in memory to guarantee identical instances across hash calculation and source code generation.
            using var snapshot = _environment.BeginSnapshot(widgetFactory, movieName, viewModelType, out failure);
            if (snapshot is null)
            {
                Report($"no fingerprint for the prepared prefabs ({failure ?? "a prefab of the movie has no recorded XML"}), XML");
                return false;
            }

            IReadOnlyList<GeneratedSource> sources;
            Dictionary<string, string> inspected;
            try
            {
                // Tracks inspected types to construct the assembly dependency list.
                using var recording = TypeDependencies.Begin();
                TypeDependencies.Inspect(viewModelType);
                sources = _environment.GenerateSources(snapshot);
                inspected = PrefabDependencies.DescribeInspected(recording.Types);
            }
            catch (Exception e)
            {
                // Catches code generation failures due to invalid XML bindings, recording the failure and falling back to XML rendering.
                RecordGenerationFailure(key, snapshot.CollectInputs().Fingerprint, e);
                RecordTiming("decide", movieName, key.Variant, stopwatch, $"fingerprint {fingerprintMilliseconds} ms, generating failed ({e.Message}), XML");
                return false;
            }

            var inputs = snapshot.CollectInputs();
            // Re-validates cache with the final fingerprint obtained after code generation, accounting for dynamic type resolutions.
            if (TryUseExisting(context, key, movieName, viewModelType, inputs.Fingerprint, out outcome) is { } settled)
            {
                Report($"fingerprint {fingerprintMilliseconds} ms, prepared inputs: {outcome}");
                return settled;
            }

            var viewModelName = viewModelType.Name;
            var job = sources.Concat([IgnoresAccessChecksSource.Create(inputs.ReferencePaths)]).ToList();
            _pending.Add(key);
            Report($"fingerprint {fingerprintMilliseconds} ms, generated {job.Sum(x => x.Content.Length) / 1024} KB of C#, compiling in the background, XML this time");
            Trace.TraceInformation("UIExtenderEx: compiling prefab '{0}' for '{1}' in the background", movieName, viewModelType.FullName);
            // Dispatches source text and metadata across thread boundaries; snapshot leases are disposed upon exiting this method.
            _environment.RunInBackground(() => CompileInBackground(key, inputs.Fingerprint, viewModelName, job, inputs.ReferencePaths, inspected));
            return false;
        }
        catch (PrefabReferenceException e)
        {
            // Handles missing or unreadable assembly dependencies by falling back to XML rendering for affected movies without disabling the manager.
            Report($"a referenced assembly cannot be read ({e.Message}), XML");
            if (_unreadableReferences.Add(e.AssemblyName))
                _environment.Warn($"Compiled prefabs cannot read '{e.AssemblyName}', movies that use it stay on XML: {e.Message}");
            return false;
        }
        catch (Exception e)
        {
            Disable(e);
            return false;
        }
    }

    /// <summary>
    /// Records a code generation failure for the specified movie key and fingerprint, suppressing repeated generation attempts until inputs change.
    /// </summary>
    private void RecordGenerationFailure(PrefabKey key, string fingerprint, Exception e)
    {
        _failed[(key, fingerprint)] = UIEnvironmentVersion.Version;
        Trace.TraceError("UIExtenderEx: generating prefab '{0}' for '{1}' failed: {2}", key.Movie, key.Variant, e);
        var failureDirectory = WriteFailure(key, [], [e.ToString()]);
        if (_warned.Add((key, fingerprint)))
            _environment.Warn($"Failed to generate code for prefab '{key.Movie}', falling back to XML: {e.Message} Details: {failureDirectory ?? "see the log"}");
    }

    /// <summary>
    /// Attempts to register a preloaded or cached build matching the specified fingerprint whose assembly dependencies remain valid.
    /// </summary>
    private bool TryUseCachedBuild(GeneratedPrefabContext context, PrefabKey key, string fingerprint)
    {
        if (TryReadFromCache(key, fingerprint) is not { } cached || !TryRegister(context, key, fingerprint, cached.Entry.Dependencies, cached.Assembly))
            return false;

        if (GetCache() is { } cache)
        {
            try
            {
                if (cache.RemoveOtherBuilds(key.Movie, key.Variant, fingerprint))
                    _environment.RunInBackground(cache.Flush);
            }
            catch (Exception e)
            {
                Trace.TraceWarning("UIExtenderEx: could not drop the older build of '{0}' for '{1}': {2}", key.Movie, key.Variant, e.Message);
            }
        }
        // Cleans up prior failure logs once a valid build is successfully registered.
        DeleteReport(PrefabCache.FailedDirectoryName, key);
        return true;
    }

    /// <summary>
    /// Whether a build for <paramref name="fingerprint"/> is already registered, still being compiled, known to fail, or on
    /// disk. Returns what <see cref="TryUseCompiledPrefab"/> should return, saying why in <paramref name="outcome"/>, or null
    /// when a build has to be prepared.
    /// </summary>
    private bool? TryUseExisting(GeneratedPrefabContext context, PrefabKey key, string movieName, Type viewModelType, string fingerprint, out string outcome)
    {
        if (_registered.TryGetValue(key, out var registered) && registered.Fingerprint == fingerprint)
        {
            if (FindChangedDependency(key, registered.Dependencies) is null)
            {
                outcome = "compiled variant already registered";
                return true;
            }
            // Built from an assembly that has since been replaced in the process; the build after it replaces the registration
            _registered.Remove(key);
        }

        if (_pending.Contains(key))
        {
            outcome = "compilation still pending, XML";
            return false;
        }

        if (_failed.TryGetValue((key, fingerprint), out var failedUnder))
        {
            if (failedUnder == UIEnvironmentVersion.Version)
            {
                outcome = "failed before, XML";
                return false;
            }
            // An assembly loaded or something was registered since: what the build was missing may be there now
            _failed.Remove((key, fingerprint));
        }

        if (TryUseCachedBuild(context, key, fingerprint))
        {
            outcome = "registered the cached build";
            return true;
        }

        outcome = string.Empty;
        return null;
    }

    /// <summary>
    /// The game clears and rescans its creators on every resource refresh. Put ours back afterwards.
    /// </summary>
    public void OnPrefabsCollected(GeneratedPrefabContext context)
    {
        // Nothing was ever cached without an environment to cache for
        if (!_environment.IsEnabled)
            return;
        OnPrefabsCollectedCore(context);
    }

    /// <remarks>Out of line for the reason given on <see cref="WarmUpCompilersCore"/>.</remarks>
    [MethodImpl(MethodImplOptions.NoInlining)]
    private void OnPrefabsCollectedCore(GeneratedPrefabContext context)
    {
        // A resource refresh replaces the factory. Movies never reopened must not retain its old tables.
        PrefabFingerprint.ClearCache();
        PrefabReferenceSet.ClearCache();
        if (IsDisabled)
            return;

        try
        {
            DrainFinished(context);
            foreach (var registered in _registered.Values)
                registered.Collect(context);
        }
        catch (Exception e)
        {
            Disable(e);
        }
    }

    /// <summary>
    /// Determines whether the specified assembly was produced by the compiled prefab runtime.
    /// </summary>
    /// <remarks>
    /// Generated assemblies are excluded from compilation reference sets and dependency graphs to prevent circular dependencies.
    /// </remarks>
    public static bool IsGeneratedAssembly(Assembly assembly) => IsGeneratedAssemblyName(assembly.GetName().Name);

    /// <summary>
    /// Determines whether the specified assembly name matches the generated prefab assembly naming convention.
    /// </summary>
    public static bool IsGeneratedAssemblyName(string? assemblyName) =>
        assemblyName is not null && assemblyName.StartsWith(GeneratedNamespace + ".", StringComparison.Ordinal);

    /// <summary>
    /// Constructs a unique assembly name for the specified movie, ViewModel type, and fingerprint key.
    /// </summary>
    public static string GetAssemblyName(string movieName, Type viewModelType, string fingerprint) =>
        GetAssemblyName(movieName, viewModelType.Name, fingerprint);

    private static string GetAssemblyName(string movieName, string viewModelName, string tag) =>
        $"{GeneratedNamespace}.{Sanitize(movieName)}.{Sanitize(viewModelName)}.{tag.Substring(0, Math.Min(16, tag.Length))}";

    /// <summary>
    /// Computes a composite build tag hash combining the fingerprint, inspected type signatures, and reference assembly MVIDs.
    /// </summary>
    private static string BuildTag(string fingerprint, IReadOnlyDictionary<string, string> inspected, IReadOnlyList<string> references)
    {
        var sb = new StringBuilder(fingerprint).Append('\n');
        foreach (var pair in inspected.OrderBy(x => x.Key, StringComparer.Ordinal))
            sb.Append(pair.Key).Append(':').Append(pair.Value).Append('\n');
        foreach (var path in references)
            sb.Append(PrefabAssemblyReference.TryRead(path)?.Mvid ?? path).Append('\n');
        return PrefabXmlRegistry.Hash(sb.ToString());
    }

    private void DrainFinished(GeneratedPrefabContext context)
    {
        while (_finished.TryDequeue(out var result))
        {
            _pending.Remove(result.Key);

            if (result.Assembly is not null && TryRegister(context, result.Key, result.Fingerprint, result.Dependencies, result.Assembly))
                continue;

            _failed[(result.Key, result.Fingerprint)] = UIEnvironmentVersion.Version;
            if (_warned.Add((result.Key, result.Fingerprint)))
                _environment.Warn($"Failed to compile prefab '{result.Key.Movie}', falling back to XML. Details: {result.FailureDirectory ?? "see the log"}");
            foreach (var error in result.Errors.Take(5))
                Trace.TraceError("UIExtenderEx: {0}", error);
        }
    }

    private bool TryRegister(GeneratedPrefabContext context, PrefabKey key, string fingerprint, IReadOnlyList<string> dependencies, Assembly assembly)
    {
        var stopwatch = Stopwatch.StartNew();
        try
        {
            if (_environment.CreateCreator(assembly) is not { } collect)
                return false;

            collect(context);
            _registered[key] = new(fingerprint, dependencies, collect);
            Trace.TraceInformation("UIExtenderEx: using compiled prefab '{0}' for '{1}'", key.Movie, key.Variant);
            RecordTiming("register", key.Movie, key.Variant, stopwatch, assembly.GetName().Name);
            return true;
        }
        catch (Exception e)
        {
            Trace.TraceError("UIExtenderEx: failed to load compiled prefab '{0}' for '{1}': {2}", key.Movie, key.Variant, e);
            return false;
        }
    }

    /// <summary>
    /// Executes compilation on a background worker thread, ensuring a result is enqueued to dequeue the key from <see cref="_pending"/>.
    /// </summary>
    private void CompileInBackground(PrefabKey key, string fingerprint, string viewModelName, IReadOnlyList<GeneratedSource> sources, IReadOnlyList<string> references,
        IReadOnlyDictionary<string, string> inspected)
    {
        try
        {
            var assemblyName = GetAssemblyName(key.Movie, viewModelName, BuildTag(fingerprint, inspected, references));
            if (GetCache() is { } cache)
                ExplainRebuild(cache, key, fingerprint);
            CompileAndReport(key, fingerprint, assemblyName, sources, references, inspected);
        }
        catch (Exception e)
        {
            Trace.TraceError("UIExtenderEx: compiling prefab '{0}' for '{1}' failed unexpectedly: {2}", key.Movie, key.Variant, e);
            _finished.Enqueue(new(key, fingerprint, [], null, [e.ToString()], null));
        }
    }

    private void CompileAndReport(PrefabKey key, string fingerprint, string assemblyName, IReadOnlyList<GeneratedSource> sources, IReadOnlyList<string> references,
        IReadOnlyDictionary<string, string> inspected)
    {
        var stopwatch = Stopwatch.StartNew();
        var errors = new List<string>();
        byte[]? assembly = null;
        IReadOnlyList<string> dependencies = [];

        var compiler = _environment.Compiler;
        try
        {
            var result = compiler.Compile(assemblyName, sources, references);
            if (result.Success)
            {
                assembly = result.Assembly;
                dependencies = PrefabDependencies.Compose(inspected, result.UsedReferencePaths);
                Trace.TraceInformation("UIExtenderEx: compiled '{0}' with {1} in {2} ms", assemblyName, compiler.Name, stopwatch.ElapsedMilliseconds);
            }
            else
            {
                errors.AddRange(result.Errors.Select(x => compiler.Name + ": " + x));
            }
        }
        catch (Exception e)
        {
            errors.Add(compiler.Name + ": " + e);
        }
        RecordTiming("compile", key.Movie, key.Variant, stopwatch, assembly is not null
            ? $"{compiler.Name}, {sources.Sum(x => x.Content.Length) / 1024} KB of C#, {assembly.Length / 1024} KB assembly"
            : $"{compiler.Name} failed with {errors.Count} errors");

        string? failureDirectory = null;
        Assembly? loaded = null;
        if (assembly is not null)
        {
            WriteToCache(key, fingerprint, assembly, dependencies, _environment.DumpGeneratedCode ? sources : null);
            // Loads the compiled assembly on the background worker thread so assembly-load listeners complete prior to movie opening.
            var loading = Stopwatch.StartNew();
            try
            {
                loaded = _environment.LoadAssembly(assembly);
                RecordTiming("load assembly", key.Movie, key.Variant, loading, "compiled, on a worker");
            }
            catch (Exception e)
            {
                errors.Add("Loading the compiled assembly failed: " + e);
            }
        }

        if (loaded is null)
            failureDirectory = WriteFailure(key, sources, errors);

        _finished.Enqueue(new(key, fingerprint, dependencies, loaded, errors, failureDirectory));
        // Flushes the cache asynchronously after enqueuing the job result to avoid delaying movie instantiation.
        if (assembly is not null)
            FlushCache();
    }

    private static string Sanitize(string text)
    {
        var sb = new StringBuilder(text.Length);
        foreach (var c in text)
            sb.Append(char.IsLetterOrDigit(c) ? c : '_');
        return sb.ToString();
    }

    /// <summary>
    /// Preloads, on a background worker thread, the cached prefab assemblies whose referenced assemblies are all loaded.
    /// </summary>
    /// <remarks>
    /// A build referencing an assembly that is not loaded yet is left for <see cref="PreloadDeferredBuilds"/> or for the movie
    /// that asks for it. Loading it now would put it in the process before what it references, and if that never arrives (a disabled
    /// module) the game's own type scans of the loaded assemblies fail on it.
    /// </remarks>
    private void PreloadCache(string stage)
    {
        if (GetCache() is not { } cache)
            return;

        var stopwatch = Stopwatch.StartNew();
        var count = 0;
        var waiting = 0;
        try
        {
            cache.ForEachBuild(entry =>
            {
                if (_cachedLoads.ContainsKey(entry.Key))
                    return false;
                if (PrefabDependencies.FindNotLoaded(entry.Dependencies) is not { } missing)
                    return true;
                waiting++;
                Trace.TraceInformation("UIExtenderEx: the cached build of '{0}' for '{1}' is not preloaded {2}, '{3}' is not loaded",
                    entry.Movie, entry.Variant, stage, missing);
                return false;
            }, (entry, bytes) =>
            {
                try
                {
                    _ = LoadOnce(entry, bytes).Assembly.Value;
                    count++;
                }
                catch (Exception e)
                {
                    Trace.TraceWarning("UIExtenderEx: could not preload the build of '{0}' for '{1}': {2}", entry.Movie, entry.Variant, e.Message);
                }
            });
        }
        catch (Exception e)
        {
            Trace.TraceWarning("UIExtenderEx: could not preload the compiled prefab cache: {0}", e.Message);
        }
        if (count > 0 || waiting > 0)
        {
            Trace.TraceInformation("UIExtenderEx: preloaded {0} cached prefab assemblies {1} in {2} ms, {3} left out", count, stage, stopwatch.ElapsedMilliseconds, waiting);
            RecordTiming("preload", null, null, stopwatch, $"{count} cached assemblies {stage}, {waiting} left out, on a worker");
        }
    }

    /// <summary>
    /// Returns the single load of a cached build, starting it from <paramref name="bytes"/> unless one is already loaded or loading.
    /// </summary>
    /// <remarks>
    /// The load runs once even when the preload and a movie ask at the same time. If it fails, the failure is remembered for the
    /// session and the movie compiles the build again.
    /// </remarks>
    private CachedLoad LoadOnce(PrefabCacheEntry entry, byte[] bytes) =>
        _cachedLoads.GetOrAdd(entry.Key, _ => new CachedLoad(entry, new Lazy<Assembly>(() => _environment.LoadAssembly(bytes))));

    /// <summary>
    /// Retrieves a valid compiled assembly for the specified key and fingerprint from preloaded memory or disk cache.
    /// </summary>
    private (PrefabCacheEntry Entry, Assembly Assembly)? TryReadFromCache(PrefabKey key, string fingerprint)
    {
        try
        {
            if (_cachedLoads.TryGetValue(PrefabCacheEntry.KeyOf(key.Movie, key.Variant, fingerprint), out var loaded))
            {
                // The disk holds the same build under this key, no need to read it again when it no longer fits
                if (FindChangedDependency(key, loaded.Entry.Dependencies) is not null)
                    return null;
                return (loaded.Entry, loaded.Assembly.Value);
            }

            if (GetCache() is not { } cache)
                return null;

            // Loads the assembly synchronously on the main thread if the preload did not, or waits for the preload loading it
            var stopwatch = Stopwatch.StartNew();
            if (cache.TryRead(key.Movie, key.Variant, fingerprint, x => FindChangedDependency(key, x.Dependencies) is null) is not { } found)
                return null;
            var load = LoadOnce(found.Entry, found.Assembly);
            var assembly = load.Assembly.Value;
            RecordTiming("load assembly", key.Movie, key.Variant, stopwatch, "cached, on the main thread");
            return (load.Entry, assembly);
        }
        catch (Exception e)
        {
            Trace.TraceWarning("UIExtenderEx: could not load the cached build of '{0}' for '{1}': {2}", key.Movie, key.Variant, e.Message);
            return null;
        }
    }

    /// <summary>
    /// Identifies the first assembly dependency whose runtime identity has changed since compilation, or <see langword="null"/> if all remain valid.
    /// </summary>
    private static string? FindChangedDependency(PrefabKey key, IReadOnlyList<string> dependencies)
    {
        if (PrefabDependencies.FindChanged(dependencies) is not { } changed)
            return null;
        Trace.TraceInformation("UIExtenderEx: the build of '{0}' for '{1}' depends on an assembly that changed: {2}", key.Movie, key.Variant, changed);
        return changed;
    }

    /// <summary>
    /// Writes a compiled assembly and its metadata to the disk cache, cleans up previous failure reports, and emits source dumps when enabled.
    /// </summary>
    private void WriteToCache(PrefabKey key, string fingerprint, byte[] assembly, IReadOnlyList<string> dependencies, IReadOnlyList<GeneratedSource>? sources)
    {
        if (GetCache() is { } cache)
        {
            try
            {
                cache.Put(key.Movie, key.Variant, fingerprint, assembly, dependencies);
            }
            catch (Exception e)
            {
                Trace.TraceWarning("UIExtenderEx: failed to cache the build of '{0}' for '{1}': {2}", key.Movie, key.Variant, e.Message);
            }
        }

        DeleteReport(PrefabCache.FailedDirectoryName, key);
        if (sources is not null)
            WriteReport(PrefabCache.SourcesDirectoryName, key, sources, null);
        else
            DeleteReport(PrefabCache.SourcesDirectoryName, key);
    }

    private void FlushCache()
    {
        try
        {
            GetCache()?.Flush();
        }
        catch (Exception e)
        {
            Trace.TraceWarning("UIExtenderEx: failed to write the compiled prefab cache: {0}", e.Message);
        }
    }

    private string? WriteFailure(PrefabKey key, IReadOnlyList<GeneratedSource> sources, IReadOnlyList<string> errors) =>
        WriteReport(PrefabCache.FailedDirectoryName, key, sources, errors);

    /// <summary>
    /// Writes diagnostic report files (sources and compiler errors) to the cache directory under <c>&lt;kind&gt;/&lt;movie&gt;/&lt;ViewModel&gt;/</c>.
    /// </summary>
    private string? WriteReport(string kind, PrefabKey key, IReadOnlyList<GeneratedSource> sources, IReadOnlyList<string>? errors)
    {
        if (GetReportPath(kind, key) is not { } report)
            return null;

        try
        {
            if (Directory.Exists(report))
                Directory.Delete(report, true);
            Directory.CreateDirectory(report);
            foreach (var source in sources)
                File.WriteAllText(Path.Combine(report, source.FileName), source.Content, Encoding.UTF8);
            if (errors is not null)
                File.WriteAllLines(Path.Combine(report, "errors.txt"), errors, Encoding.UTF8);
            return report;
        }
        catch (Exception e)
        {
            Trace.TraceWarning("UIExtenderEx: could not write '{0}': {1}", report, e.Message);
            return null;
        }
    }

    private void DeleteReport(string kind, PrefabKey key)
    {
        if (GetReportPath(kind, key) is not { } report)
            return;

        try
        {
            if (Directory.Exists(report))
                Directory.Delete(report, true);
        }
        catch (Exception e)
        {
            Trace.TraceWarning("UIExtenderEx: could not delete '{0}': {1}", report, e.Message);
        }
    }

    /// <summary>Resolves the target file path for a diagnostic report within the cache directory.</summary>
    private string? GetReportPath(string kind, PrefabKey key)
    {
        // Once the cache had its chance to clear the folder
        GetCache();
        return _environment.CacheDirectory is { } directory
            ? Path.Combine(directory, kind, PrefabCache.GetPairPath(key.Movie, key.Variant).Replace('/', Path.DirectorySeparatorChar))
            : null;
    }

    /// <summary>
    /// Opens or retrieves the active <see cref="PrefabCache"/> instance for the session.
    /// </summary>
    /// <remarks>
    /// Recreates the cache directory if the stored generation hash does not match the active runtime or game binaries.
    /// </remarks>
    private PrefabCache? GetCache()
    {
        if (_environment.CacheDirectory is not { } directory)
            return null;

        lock (_cacheLock)
        {
            if (_cacheChecked)
                return _cache;
            _cacheChecked = true;

            try
            {
                _cache = new PrefabCache(directory, _environment.CacheGeneration, _environment.SeedCaches);
            }
            catch (Exception e)
            {
                Trace.TraceWarning("UIExtenderEx: the compiled prefab cache is unavailable, prefabs are recompiled every session: {0}", e);
            }
            return _cache;
        }
    }

    /// <summary>
    /// Logs diagnostic information explaining why an existing cached build was rejected and queued for recompilation.
    /// </summary>
    private static void ExplainRebuild(PrefabCache cache, PrefabKey key, string fingerprint)
    {
        try
        {
            if (cache.FindBuildOf(key.Movie, key.Variant) is not { } previous)
                return;
            if (previous.Fingerprint == fingerprint)
            {
                // Keyed the same: what changed is an assembly the build depends on, which the check that refused it traced
                Trace.TraceInformation("UIExtenderEx: prefab '{0}' for '{1}' is rebuilt because an assembly it depends on changed: {2}",
                    key.Movie, key.Variant, PrefabDependencies.FindChanged(previous.Dependencies) ?? "(none differs now)");
                return;
            }
            Trace.TraceInformation("UIExtenderEx: prefab '{0}' for '{1}' is rebuilt because its inputs changed since fingerprint {2}",
                key.Movie, key.Variant, previous.Fingerprint);
        }
        catch (Exception e)
        {
            Trace.TraceWarning("UIExtenderEx: could not tell why '{0}' is rebuilt: {1}", key.Movie, e.Message);
        }
    }

    /// <summary>
    /// Records load duration metrics for a movie invocation, indicating whether it was served by XML or compiled assemblies.
    /// </summary>
    public void RecordMovieLoad(string movieName, string variant, double milliseconds, string servedBy)
    {
        try
        {
            Timings?.Record("load movie", movieName, variant, milliseconds, servedBy);
        }
        catch (Exception e)
        {
            Trace.TraceWarning("UIExtenderEx: could not record the load of '{0}': {1}", movieName, e.Message);
        }
    }

    /// <summary>Records an execution phase timing metric to <see cref="Timings"/>.</summary>
    private void RecordTiming(string what, string? movie, string? variant, Stopwatch stopwatch, string? detail)
    {
        try
        {
            Timings?.Record(what, movie, variant, stopwatch.Elapsed.TotalMilliseconds, detail);
        }
        catch (Exception e)
        {
            Trace.TraceWarning("UIExtenderEx: could not record a timing of '{0}': {1}", what, e.Message);
        }
    }

    /// <summary>
    /// Gets the <see cref="PrefabTimings"/> session recorder if timing collection is enabled and a cache directory is available.
    /// </summary>
    private PrefabTimings? Timings
    {
        get
        {
            if (!_environment.RecordTimings || _environment.CacheDirectory is not { } directory)
                return null;
            lock (_timingsLock)
                return _timings ??= new PrefabTimings(directory, _sessionStart, Process.GetCurrentProcess().Id, _environment.RunInBackground);
        }
    }

    private void Disable(Exception e)
    {
        IsDisabled = true;
        Trace.TraceError("UIExtenderEx: compiled prefabs disabled for this session: {0}", e);
        _environment.Warn($"Compiled prefabs disabled for this session, using XML prefabs: {e.Message}");
    }
}