using NUnit.Framework;

using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.CompilerServices;
using System.Text.RegularExpressions;

namespace Bannerlord.UIExtenderEx.Tests.CodeGenerator;

/// <summary>
/// Generated code names every type from <c>global::</c>. An unrooted name is looked up through the namespaces enclosing the
/// generated code first - <c>Bannerlord.UIExtenderEx.AutoGenerated</c>, <c>Bannerlord.UIExtenderEx</c>, <c>Bannerlord</c> -
/// which any assembly can put a type or a namespace of that name into, and what the code binds to would then depend on an
/// assembly no build records as a dependency (CompiledPrefabs' PrefabDependencies).
/// <para>
/// Checked over every snapshot, which between them cover what the generator emits: a name written without the root shows
/// up here once its snapshot is accepted.
/// </para>
/// </summary>
public class RootedNamesTests
{
    private static readonly Regex StringLiteral = new(@"@?""(?:[^""\\]|\\.)*""", RegexOptions.Compiled);
    private static readonly Regex Unrooted = new(@"(?<![\w.:])(?:TaleWorlds|System|Bannerlord|Microsoft)\.(?=[A-Za-z_])", RegexOptions.Compiled);

    [Test]
    public void EverySnapshot_NamesTypesFromTheGlobalNamespace()
    {
        var snapshots = Directory.GetFiles(Path.Combine(SourceDirectory(), "Snapshots"), "*.verified.cs");
        Assert.That(snapshots, Is.Not.Empty, "test premise: the snapshots are there to read");

        var unrooted = new List<string>();
        foreach (var file in snapshots)
        {
            var lines = File.ReadAllLines(file);
            for (var i = 0; i < lines.Length; i++)
            {
                var line = lines[i].Trim();
                if (line.StartsWith("namespace ", StringComparison.Ordinal) || line.StartsWith("//", StringComparison.Ordinal))
                    continue;
                var code = StringLiteral.Replace(line, "\"\"");
                var comment = code.IndexOf("//", StringComparison.Ordinal);
                if (comment >= 0)
                    code = code.Substring(0, comment);
                if (Unrooted.IsMatch(code))
                    unrooted.Add($"{Path.GetFileName(file)}:{i + 1}: {line}");
            }
        }

        Assert.That(unrooted, Is.Empty);
    }

    private static string SourceDirectory([CallerFilePath] string path = "") => Path.GetDirectoryName(path)!;
}
