using Bannerlord.UIExtenderEx.GauntletUI.CodeGenerator.Extensions;
using Bannerlord.UIExtenderEx.GauntletUI.CodeGenerator.Prefabs;
using Bannerlord.UIExtenderEx.GauntletUI.CodeGenerator.Widgets;

using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;

using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.PrefabSystem;
using TaleWorlds.Library;
using TaleWorlds.Library.CodeGeneration;

namespace Bannerlord.UIExtenderEx.GauntletUI.CodeGenerator.Databinding;

/// <summary>Represents the item template classes associated with a bound list, including the default template and optional first- or last-item variants.</summary>
internal sealed record ItemTemplateClasses(PrefabClass Default, PrefabClass? First, PrefabClass? Last);

/// <summary>
/// Encapsulates databinding configuration for a single widget extracted from its template in accordance with <c>PrefabDatabindingExtension.AfterAttributesSet</c>,
/// including target data source paths, property/command bindings, and child item templates.
/// </summary>
internal sealed class WidgetBinding
{
    private readonly PrefabClass _owner;

    private readonly WidgetTemplate _template;

    private Type? _actualRootDataSourceType;

    private Type? _dataSourceType;

    private BindingPath? _bindingPath;

    private bool _usesParentsDatabinding;

    private bool _rootUsesSubPath;

    /// <summary>Stores the data source path supplied to the view by this widget (declared or inherited), or <see langword="null"/> if none is specified.</summary>
    private string? _viewDataSourceText;

    /// <summary>Captures the surrounding binding scope for a widget consuming an external prefab prior to establishing a custom view data source. See <see cref="PrefabDataSourcePath"/>.</summary>
    private (BindingPath Path, Type? Type)? _scopeAround;

    /// <summary>Indicates whether this widget adopts the root data source of its referenced prefab rather than declaring an explicit data source.</summary>
    private bool _takesUsedPrefabDataSource;

    /// <summary>Indicates whether this widget template explicitly declares a data source that overrides the root data source of any referenced prefab.</summary>
    private bool _declaresDataSource;

    /// <summary>Stores the surrounding binding path when adopting the root data source of a referenced prefab. See <see cref="GetUsedPrefabDataSource"/>.</summary>
    private BindingPath? _prefabDataSourcePath;

    private Type? _prefabDataSourceType;

    /// <summary>Stores the relative path applied at the prefab root when supplied with an outer scope above the immediate widget context. See <see cref="HandPrefabTheScopeAround"/>.</summary>
    private string? _prefabRootDataSource;

    public WidgetBinding(WidgetNode widget)
    {
        Widget = widget;
        _owner = widget.Owner;
        _template = widget.Template;
    }

    public WidgetNode Widget { get; }

    public WidgetBinding? Parent => Widget.Parent?.Databinding;

    [MemberNotNullWhen(false, nameof(Parent))]
    public bool IsRoot => Parent == null;

    public Dictionary<string, PropertyBinding> PropertyBindings { get; } = new();

    private IReadOnlyList<string>? _writebackNotifications;

    /// <summary>
    /// Gets the set of property change notifications monitored for two-way writeback. Matches the specific properties raised
    /// in widget IL (via <see cref="WidgetRaises"/>), or all nine standard notifications if static IL analysis cannot determine
    /// the exact raise set.
    /// </summary>
    public IReadOnlyList<string> WritebackNotifications => _writebackNotifications ??= WidgetRaises.Needed(
        _owner.WidgetFactory.TryGetWidgetTypeWithinPrefabRoots(_template.Type, out var widgetType) ? widgetType : null,
        PropertyBindings.Values.Select(x => x.Property), out _);

    public Dictionary<string, CommandBinding> CommandBindings { get; } = new();

    /// <summary>Gets the generated item template classes for the list driven by this widget, or <see langword="null"/> if this widget is not a bound list container.</summary>
    public ItemTemplateClasses? ItemTemplates { get; private set; }

    /// <summary>
    /// Indicates whether this widget declares item template usage. Inspects raw template extension data directly so queries
    /// succeed even before item template classes are constructed or when element types fail resolution.
    /// </summary>
    public bool HasItemTemplateUsage => _template.GetExtensionData<ItemTemplateUsage>() != null;

    /// <summary>
    /// Indicates whether items of the bound list are generated by the referenced prefab's root template rather than this widget's template.
    /// <para>
    /// Gauntlet UI unifies an instantiated widget and its referenced prefab root into a single view (<c>PrefabDatabindingExtension.OnWidgetCreated</c>),
    /// adopting item templates from whichever template defines them. When a prefab root defines item templates, its generated class
    /// manages item instantiation.
    /// </para>
    /// </summary>
    public bool ItemsBuiltByUsedPrefab
    {
        get
        {
            if (HasItemTemplateUsage)
            {
                return false;
            }
            // Traverse template hierarchies to resolve nested prefab roots that define item template usage.
            var template = _template;
            var visited = new HashSet<string>(StringComparer.Ordinal);
            while (visited.Add(template.Type) && _owner.WidgetFactory.TryGetCustomTypeIncludingRegistered(template.Type, out var prefab) && prefab.RootTemplate is { } root)
            {
                if (root.GetExtensionData<ItemTemplateUsage>() != null)
                {
                    return true;
                }
                template = root;
            }
            return false;
        }
    }

    /// <summary>
    /// Gets the local binding path established during <see cref="Initialize"/>.
    /// </summary>
    private BindingPath BindingPath => _bindingPath
        ?? throw new InvalidOperationException($"The databinding of widget '{_template.Type}' was read before it was initialized.");

    public BindingPath FullBindingPath => ToLoaderPath(RawBindingPath, _owner);

    /// <summary>
    /// Gets the raw hierarchical binding path propagated down the view tree before normalization. Preserves ascendant paths targeting
    /// scopes above the movie root until final loader resolution. See <see cref="ToLoaderPath"/>.
    /// </summary>
    public BindingPath RawBindingPath => IsRoot
        ? BindingPath
        : _usesParentsDatabinding ? Parent.ChildrenRawBindingPath : Parent.ChildrenRawBindingPath.Append(BindingPath).Simplify();

    /// <summary>Gets the raw binding path scope inherited by child widgets. See <see cref="PassChildrenThrough"/>.</summary>
    private BindingPath ChildrenRawBindingPath => _childrenRawBindingPath ?? RawBindingPath;

    private Type? ChildrenDataSourceType => _childrenRawBindingPath is null ? _dataSourceType : _childrenDataSourceType;

    private BindingPath? _childrenRawBindingPath;

    private Type? _childrenDataSourceType;

    /// <summary>
    /// Configures children of a widget consuming an external prefab with a logical children location to inherit that location's binding scope.
    /// <para>
    /// <c>WidgetTemplate.CreateWidgets</c> inserts child elements under the target logical location widget, while <c>PrefabDatabindingExtension</c>
    /// establishes corresponding parent-child view relationships. Children bind within the logical location's scope rather than the outer widget's scope.
    /// </para>
    /// </summary>
    public void PassChildrenThrough(PrefabClass used)
    {
        if (used.LogicalChildrenLocationNode?.Databinding is not { } location)
        {
            return;
        }
        var rootRaw = HandsItsPrefabTheScopeAround ? OuterPath.ToRaw(PrefabDataSourcePath) : RawBindingPath;
        var locationRaw = location.RawBindingPath;
        // Strip the initial 'Root' segment for paths rooted in the class, or prepend parent traversal when navigating outside the root.
        var relative = locationRaw.Nodes.Length > 0 && locationRaw.Nodes[0] == "Root"
            ? locationRaw.Nodes.Skip(1)
            : new[] { ".." }.Concat(locationRaw.Nodes);
        _childrenRawBindingPath = rootRaw.Append(new BindingPath(relative)).Simplify();
        _childrenDataSourceType = ViewModelPaths.GetTypeAtPath(RootDataSourceType, ToLoaderPath(_childrenRawBindingPath, _owner));
    }

    private Type? RootDataSourceType => IsRoot ? _rootUsesSubPath ? _actualRootDataSourceType : _dataSourceType : Parent.RootDataSourceType;

    /// <summary>
    /// Gets the data source binding path supplied to the instantiated prefab class.
    /// <para>
    /// Evaluates to the widget's own path unless the widget supplies an overriding view data source without local bindings. In that scenario,
    /// hands the surrounding scope to the referenced prefab so its internal relative paths (such as parent navigation) resolve correctly.
    /// </para>
    /// </summary>
    public BindingPath PrefabDataSourcePath => _prefabDataSourcePath ?? FullBindingPath;

    /// <summary>Indicates whether the referenced prefab receives an external surrounding scope rather than this widget's direct binding path.</summary>
    public bool HandsItsPrefabTheScopeAround => _prefabDataSourcePath is not null;

    /// <summary>
    /// Indicates whether the referenced prefab is bound to its enclosing scope, receiving data source assignments and disposal notifications along with that scope.
    /// </summary>
    public bool BindsItsPrefabAtItsScope => !Widget.IsBuiltin && !IsRoot && !HandsItsPrefabTheScopeAround;

    /// <summary>
    /// Normalizes a binding path to match Gauntlet XML loader path evaluation semantics.
    /// <para>
    /// In TaleWorlds Gauntlet UI, ascending paths from the movie root simplify to empty or parent traversals that evaluate back to the movie root itself
    /// (<c>GauntletMovie.GetViewModelAtPath</c>). For movie classes, normalizes these redundant root traversals to <c>Root</c>.
    /// For prefabs and item templates, preserves outer scope climbs as <see cref="OuterPath"/> instances resolved by the host container.
    /// </para>
    /// </summary>
    public static BindingPath ToLoaderPath(BindingPath path, PrefabClass owner)
    {
        // Simplify the binding path first to eliminate adjacent navigation hops.
        var simplified = path.Simplify();
        // When escaping the local root in non-movie classes, count parent navigations and create an OuterPath.
        if ((simplified.Nodes.Length == 0 || simplified.Nodes[0] != "Root") && owner.Kind != PrefabClassKind.Movie)
        {
            var climbs = simplified.Nodes.TakeWhile(x => x == "..").Count();
            return OuterPath.Create(climbs + 1, simplified.Nodes.Skip(climbs));
        }
        return simplified.SubPath is { } rest ? new BindingPath("Root").Append(rest) : new BindingPath("Root");
    }

    /// <summary>
    /// Translates a child class outer path into the coordinate space of the current host class, applying host-level path normalization.
    /// </summary>
    public BindingPath ToHostPath(BindingPath classRootRaw, BindingPath classPath) => ToLoaderPath(OuterPath.Below(classRootRaw, classPath), _owner);

    /// <summary>
    /// Enumerates all child prefab and item template classes that receive a root data source from this widget, alongside their raw host paths.
    /// </summary>
    public IEnumerable<(PrefabClass Class, BindingPath RootRaw, bool IsItem)> ClassesHandedADataSource()
    {
        if (Widget.UsedClass is { Databinding: not null } used)
        {
            // The base class shares this class's data source (base.SetDataSource); referenced prefabs receive their designated scope.
            var rootRaw = IsRoot
                ? new BindingPath("Root")
                : HandsItsPrefabTheScopeAround ? OuterPath.ToRaw(PrefabDataSourcePath) : RawBindingPath;
            yield return (used, rootRaw, false);
        }
        if (ItemTemplates is { } templates)
        {
            // Item bindings target list indices that cancel during parent navigation.
            var itemRaw = RawBindingPath.Append(new BindingPath(0));
            foreach (var template in new[] { templates.Default, templates.First, templates.Last })
            {
                if (template is { Databinding: not null })
                    yield return (template, itemRaw, true);
            }
        }
    }

    /// <summary>
    /// Indicates whether the root view of this class ignores declared data source attributes.
    /// <para>
    /// Applies to top-level movie roots, list item templates (where <c>GauntletView.AddItemToList</c> binds items by index regardless of declared paths),
    /// and prefabs where the caller explicitly overrides the root data source.
    /// </para>
    /// </summary>
    public bool IgnoresRootDataSource =>
        _owner.Kind is PrefabClassKind.Movie or PrefabClassKind.ItemTemplate || _owner.Options.IgnoresRootDataSource;

    private string[] InheritedOverriddenCommands =>
        IsRoot && _owner.Options.OverriddenCommands is { } names ? names.Split(',') : [];

    private string? RootDataSourceOverride => IsRoot ? _owner.Options.RootDataSource : null;

    public void Initialize()
    {
        if (IsRoot)
        {
            _dataSourceType = _owner.Options.DataSourceType;
            _actualRootDataSourceType = _dataSourceType;
            _bindingPath = new("Root");
            _usesParentsDatabinding = false;
        }
        else
        {
            _dataSourceType = Parent.ChildrenDataSourceType;
            _bindingPath = Parent._bindingPath;
            _usesParentsDatabinding = true;
        }
        ReadAttributes();
        InitializeCommandBindings();
        InitializeDataBindings();
    }

    /// <summary>
    /// Constructs code generation options for the referenced or root prefab class.
    /// <para>
    /// Falls back to <see cref="ViewModel"/> when static scope types cannot be determined, maintaining typed access for standard
    /// <see cref="ViewModel"/> members while deferring custom members to dynamic lookup.
    /// </para>
    /// </summary>
    public PrefabClassOptions OptionsForUsedPrefab()
    {
        // Default unresolved list item scopes to IMBBindingList.
        var options = new PrefabClassOptions((HandsItsPrefabTheScopeAround ? _prefabDataSourceType : _dataSourceType)
                                             ?? (!HandsItsPrefabTheScopeAround && ItemsBuiltByUsedPrefab ? typeof(IMBBindingList) : typeof(ViewModel)));
        // The view at the root of the movie is bound at Root whatever any template on it declares. Elsewhere, an explicit widget data source
        // overrides the prefab root's declared data source.
        if (IsRoot && IgnoresRootDataSource)
        {
            options = options with { IgnoresRootDataSource = true };
        }
        else if (HandsItsPrefabTheScopeAround)
        {
            // Apply a declared or inherited data source at the prefab root.
            options = options with { RootDataSource = _prefabRootDataSource ?? _viewDataSourceText };
        }
        else if (_viewDataSourceText is not null || _takesUsedPrefabDataSource)
        {
            // Apply the supplied data source directly, superseding the root template's declaration.
            options = options with { IgnoresRootDataSource = true };
        }
        // Propagate command binding overrides down the prefab inheritance chain.
        var overridden = new SortedSet<string>(CommandBindings.Keys, StringComparer.Ordinal);
        overridden.UnionWith(InheritedOverriddenCommands);
        return overridden.Count > 0 ? options with { OverriddenCommands = string.Join(",", overridden) } : options;
    }

    /// <summary>
    /// Emits code attaching a <see cref="GeneratedWidgetData"/> component to the widget if not already present.
    /// <para>
    /// Ensures every widget carries its active data source context to support command parameter resolution (<c>GauntletView.ConvertCommandParameter</c>).
    /// </para>
    /// </summary>
    public void AddDataComponent(MethodCode methodCode)
    {
        var variable = Widget.VariableName;
        methodCode.AddLine("//Requires data component");
        // Guard against attaching duplicate data components when widgets are processed across multiple class boundaries.
        methodCode.AddBlock(null, () => methodCode.AddBlock($"if ({variable}.GetComponent<global::TaleWorlds.GauntletUI.Data.GeneratedWidgetData>() == null)", () =>
        {
            methodCode.AddLine($"var widgetComponent = new global::TaleWorlds.GauntletUI.Data.GeneratedWidgetData({variable});");
            methodCode.AddLine($"{variable}.AddComponent(widgetComponent);");
        }));
    }

    /// <summary>Assigns a data source path to the widget's view, preserving the outer scope for consumed prefabs. See <see cref="PrefabDataSourcePath"/>.</summary>
    private void ApplyDataSource(string bindingPathText)
    {
        KeepScopeAround();
        _viewDataSourceText = bindingPathText;
        AssignBindingPathFromValue(bindingPathText);
    }

    private void KeepScopeAround()
    {
        if (_owner.WidgetFactory.IsCustomTypeIncludingRegistered(_template.Type))
        {
            _scopeAround = (FullBindingPath, _dataSourceType);
        }
    }

    /// <summary>Instantiates generated item template classes for a bound list using the resolved item element type.</summary>
    private void CreateItemTemplates()
    {
        if (_template.GetExtensionData<ItemTemplateUsage>() is not { } usage || GetItemDataSourceType() is not { } itemDataSourceType)
        {
            return;
        }

        var options = new PrefabClassOptions(itemDataSourceType);
        var defaultTemplate = PrefabClass.CreateForItemTemplate(_owner, usage.DefaultItemTemplate, "ItemTemplate", options);
        var firstTemplate = usage.FirstItemTemplate is { } first ? PrefabClass.CreateForItemTemplate(_owner, first, "FirstItemTemplate", options) : null;
        var lastTemplate = usage.LastItemTemplate is { } last ? PrefabClass.CreateForItemTemplate(_owner, last, "LastItemTemplate", options) : null;
        ItemTemplates = new(defaultTemplate, firstTemplate, lastTemplate);
    }

    /// <summary>
    /// Resolves the data source type for individual list items.
    /// <para>
    /// Returns the generic element type when known, falls back to <see cref="ViewModel"/> for unresolved list collections,
    /// or returns <see langword="null"/> if the data source is not a collection.
    /// </para>
    /// </summary>
    private Type? GetItemDataSourceType()
    {
        if (_dataSourceType is not { } dataSourceType)
        {
            return typeof(ViewModel);
        }
        if (!typeof(IMBBindingList).IsAssignableFrom(dataSourceType))
        {
            return null;
        }
        return ViewModelPaths.GetElementType(dataSourceType) ?? typeof(ViewModel);
    }

    private void ReadAttributes()
    {
        var values = _owner.Values;
        foreach (var attribute in _template.AllAttributes)
        {
            var valueType = attribute.ValueType;
            var attributeKey = attribute.Key;
            var attributeValue = attribute.Value;
            switch (attribute.KeyType)
            {
                case WidgetAttributeKeyTypeDataSource:
                    // In accordance with PrefabDatabindingExtension.AfterAttributesSet, the movie root always binds at Root.
                    // A referenced prefab's root data source is overridden by any data source supplied by the consuming widget.
                    if (IsRoot && (IgnoresRootDataSource || RootDataSourceOverride is not null))
                    {
                        break;
                    }
                    switch (valueType)
                    {
                        case WidgetAttributeValueTypeBindingPath:
                            ApplyDataSource(attributeValue);
                            break;
                        case WidgetAttributeValueTypeParameter:
                        {
                            // Evaluate declared default parameter value unless overridden by an explicit binding path parameter.
                            var parameterValue = values.GetParameterDefaultValue(attributeValue);
                            if (values.BindingParameters.TryGetValue(attributeValue, out var givenPath) && givenPath.ValueType is WidgetAttributeValueTypeBindingPath)
                            {
                                parameterValue = givenPath.Value;
                            }
                            if (!string.IsNullOrEmpty(parameterValue))
                            {
                                ApplyDataSource(parameterValue);
                            }
                            break;
                        }
                        case WidgetAttributeValueTypeConstant:
                        {
                            // Evaluate declared constant value; ignore empty strings.
                            var constantValue = values.GetConstantValue(attributeValue);
                            if (!string.IsNullOrEmpty(constantValue))
                            {
                                ApplyDataSource(constantValue);
                            }
                            break;
                        }
                    }
                    break;
                case WidgetAttributeKeyTypeAttribute or WidgetAttributeKeyTypeId:
                    switch (valueType)
                    {
                        case WidgetAttributeValueTypeBinding:
                            AddPropertyBinding(new PropertyBinding(attributeKey, attributeValue));
                            break;
                        // Adopt property binding passed via parameter; ignore empty paths.
                        case WidgetAttributeValueTypeParameter
                            when values.BindingParameters.TryGetValue(attributeValue, out var givenBinding)
                                 && givenBinding.ValueType is WidgetAttributeValueTypeBinding
                                 && !string.IsNullOrEmpty(givenBinding.Value):
                            AddPropertyBinding(new PropertyBinding(attributeKey, givenBinding.Value));
                            break;
                    }
                    break;
                case WidgetAttributeKeyTypeCommand:
                {
                    // Skip commands overridden by the consuming widget (see PrefabClassOptions.OverriddenCommands).
                    if (Array.IndexOf(InheritedOverriddenCommands, attributeKey) >= 0)
                    {
                        break;
                    }
                    var commandPath = attributeValue;
                    if (valueType is WidgetAttributeValueTypeParameter && values.BindingParameters.TryGetValue(attributeValue, out var givenParameter))
                    {
                        commandPath = givenParameter.Value;
                    }
                    var commandBinding = new CommandBinding(attributeKey, commandPath);
                    CommandBindings.Add(commandBinding.Command, commandBinding);
                    break;
                }
            }
        }
        if (!IgnoresRootDataSource && RootDataSourceOverride is { } handedDown)
        {
            ApplyDataSource(handedDown);
        }
        if (!_declaresDataSource && !(IsRoot && IgnoresRootDataSource) && GetUsedPrefabDataSource() is { } usedDataSource)
        {
            KeepScopeAround();
            AssignBindingPathFromValue(usedDataSource);
            // Adopt the referenced prefab's root data source without declaring a new one.
            _declaresDataSource = false;
            _takesUsedPrefabDataSource = true;
        }
        // Provide the surrounding scope only when the widget declares no local bindings at the shared scope,
        // preventing duplicate view property change events.
        if (_scopeAround is { } scopeAround && (PropertyBindings.Count == 0 || IsAboveTheMovieRoot))
        {
            HandPrefabTheScopeAround(scopeAround.Path, scopeAround.Type);
        }
        ReadCommandParameters();
        CreateItemTemplates();
    }

    /// <summary>
    /// Hands the referenced prefab the surrounding scope or the common ancestor scope if relative navigation traverses upward.
    /// </summary>
    /// <summary>
    /// Indicates whether the widget's own path navigates above the movie root.
    /// </summary>
    private bool IsAboveTheMovieRoot => _owner.Kind == PrefabClassKind.Movie && (RawBindingPath.Nodes.Length == 0 || RawBindingPath.Nodes[0] != "Root");

    private void HandPrefabTheScopeAround(BindingPath scopePath, Type? scopeType)
    {
        // Above the movie root, map child paths relative to the host class scope.
        if (IsAboveTheMovieRoot && _viewDataSourceText is { } dataSource)
        {
            _prefabDataSourcePath = scopePath;
            _prefabDataSourceType = scopeType;
            _prefabRootDataSource = dataSource;
            return;
        }
        // If the scope is an outer path, delegate resolution directly to the host container.
        if (OuterPath.IsOuter(scopePath))
        {
            return;
        }
        var ownPath = FullBindingPath;
        var common = 0;
        while (common < scopePath.Nodes.Length && common < ownPath.Nodes.Length && scopePath.Nodes[common] == ownPath.Nodes[common])
        {
            common++;
        }
        if (common == scopePath.Nodes.Length && common < ownPath.Nodes.Length)
        {
            _prefabDataSourcePath = scopePath;
            _prefabDataSourceType = scopeType;
            return;
        }
        // When paths share no common ancestor, supply the data source path directly.
        if (common == ownPath.Nodes.Length || common == 0)
        {
            return;
        }
        var commonPath = new BindingPath(scopePath.Nodes.Take(common));
        _prefabDataSourcePath = commonPath;
        _prefabDataSourceType = ViewModelPaths.GetTypeAtPath(RootDataSourceType, commonPath);
        _prefabRootDataSource = new BindingPath(ownPath.Nodes.Skip(common)).Path;
    }

    private void AddPropertyBinding(PropertyBinding binding) => PropertyBindings.Add(binding.Property, binding);

    /// <summary>
    /// Resolves the data source defined by the root of a referenced prefab when the consuming widget declares none.
    /// <para>
    /// <c>PrefabDatabindingExtension.AfterAttributesSet</c> binds a prefab instance and its root widget to a shared view,
    /// allowing instance-level bindings and child widgets to evaluate against the prefab root's data source.
    /// </para>
    /// </summary>
    private string? GetUsedPrefabDataSource()
    {
        var widgetFactory = _owner.WidgetFactory;
        var template = _template;
        var parameters = _owner.Values.BindingParameters;
        var visited = new HashSet<string>(StringComparer.Ordinal);
        while (visited.Add(template.Type) && widgetFactory.TryGetCustomTypeIncludingRegistered(template.Type, out var prefab) && prefab.RootTemplate is { } root)
        {
            // Collate parameter attributes passed to the referenced prefab.
            var given = new Dictionary<string, WidgetAttributeTemplate>();
            foreach (var attribute in template.GetAttributesOf<WidgetAttributeKeyTypeParameter>())
            {
                given[attribute.Key] = attribute;
            }
            foreach (var parameter in parameters)
            {
                if (!given.ContainsKey(parameter.Key))
                {
                    given.Add(parameter.Key, parameter.Value);
                }
            }

            if (root.GetFirstAttributeIfExist<WidgetAttributeKeyTypeDataSource>() is { } dataSource)
            {
                string? path = null;
                switch (dataSource.ValueType)
                {
                    case WidgetAttributeValueTypeBindingPath:
                        path = dataSource.Value;
                        break;
                    case WidgetAttributeValueTypeParameter:
                        path = prefab.GetParameterDefaultValue(dataSource.Value);
                        if (given.TryGetValue(dataSource.Value, out var givenPath) && givenPath.ValueType is WidgetAttributeValueTypeBindingPath)
                        {
                            path = givenPath.Value;
                        }
                        break;
                    case WidgetAttributeValueTypeConstant:
                        // Resolve constant resource; invalid or recursive constants throw in parity with the XML loader.
                        var constant = prefab.GetConstantValue(dataSource.Value)
                            ?? throw new InvalidOperationException($"Prefab '{template.Type}' takes its DataSource from constant '{dataSource.Value}', which it does not define.");
                        if (ConstantResourceAnalysis.ReferencesItself(constant, prefab.Constants))
                        {
                            throw new InvalidOperationException($"Prefab '{template.Type}' takes its DataSource from constant '{dataSource.Value}', which refers to itself.");
                        }
                        path = constant.GetValue(_owner.Generator.BrushFactory, _owner.Generator.SpriteData, prefab.Constants, given, prefab.Parameters);
                        break;
                }
                // Empty paths do not establish a data source.
                return string.IsNullOrEmpty(path) ? null : path;
            }

            template = root;
            parameters = given;
        }
        return null;
    }

    /// <summary>
    /// Associates each <c>CommandParameter.X</c> attribute with its corresponding command binding.
    /// <para>
    /// Matches <see cref="PrefabDatabindingExtension"/> by iterating over registered commands and querying parameter attributes,
    /// ensuring order independence and ignoring extraneous parameter attributes.
    /// </para>
    /// </summary>
    private void ReadCommandParameters()
    {
        var commandParameters = new Dictionary<string, WidgetAttributeTemplate>();
        foreach (var attribute in _template.GetAttributesOf<WidgetAttributeKeyTypeCommandParameter>())
        {
            commandParameters[attribute.Key] = attribute;
        }

        foreach (var commandBinding in CommandBindings.Values)
        {
            if (!commandParameters.TryGetValue(commandBinding.Command, out var attribute))
            {
                continue;
            }

            string? parameter = null;
            if (attribute.ValueType is WidgetAttributeValueTypeDefault)
            {
                parameter = attribute.Value;
            }
            else if (_owner.Values.BindingParameters.TryGetValue(attribute.Value, out var givenParameter))
            {
                // Only accept parameters explicitly supplied by an enclosing prefab; ignore default fallbacks.
                parameter = givenParameter.Value;
            }

            if (!string.IsNullOrEmpty(parameter))
            {
                commandBinding.Parameter = parameter;
            }
        }
    }

    private void InitializeCommandBindings()
    {
        foreach (var commandBinding in CommandBindings.Values)
        {
            var commandPath = new BindingPath(commandBinding.Path);
            var ownerType = ViewModelPaths.GetTypeAtPath(RootDataSourceType, GetCommandOwnerPath(commandBinding));
            var method = ViewModelMemberResolution.GetMethod(ownerType, commandPath.LastNode, out var mixinType);
            commandBinding.MixinType = mixinType;
            commandBinding.FallsBackToViewModel = mixinType != null && ViewModelMemberResolution.ViewModelAnswersCommand(ownerType, commandPath.LastNode);
            commandBinding.Method = method;
        }
    }

    /// <summary>
    /// Resolves the target data source path for executing a command binding.
    /// <para>
    /// Evaluates dotted parent path segments relative to the current widget binding path and applies loader path normalization.
    /// </para>
    /// </summary>
    public BindingPath GetCommandOwnerPath(CommandBinding commandBinding)
    {
        var commandPath = new BindingPath(commandBinding.Path);
        return commandPath.Nodes.Length > 1 ? ToLoaderPath(RawBindingPath.Append(commandPath.ParentPath), _owner) : FullBindingPath;
    }

    private void InitializeDataBindings()
    {
        foreach (var propertyBinding in PropertyBindings.Values)
        {
            var viewModelType = ViewModelPaths.GetTypeAtPath(RootDataSourceType, FullBindingPath);
            var viewModelProperty = ViewModelMemberResolution.GetProperty(viewModelType, propertyBinding.Path, out var mixinType);
            propertyBinding.MixinType = mixinType;
            propertyBinding.FallsBackToViewModel = mixinType != null && ViewModelMemberResolution.ViewModelAnswersProperty(viewModelType, propertyBinding.Path);
            propertyBinding.ViewModelPropertyType = viewModelProperty?.PropertyType;
            propertyBinding.BindsByName = viewModelProperty == null && ViewModelMemberResolution.DeclaresNoMember(viewModelType, propertyBinding.Path);

            _owner.WidgetFactory.TryGetWidgetTypeWithinPrefabRoots(_template.Type, out var widgetType);
            var widgetProperty = WidgetPropertyPath.Resolve(widgetType, propertyBinding.Property);
            // Ignore indexer properties (e.g. 'Item') because indexers require argument lists and cannot be directly assigned via standard property setters.
            if (widgetProperty != null && widgetProperty.GetIndexParameters().Length != 0)
            {
                widgetProperty = null;
            }
            propertyBinding.WidgetProperty = widgetProperty;
        }
    }

    private void AssignBindingPathFromValue(string bindingPathText)
    {
        var bindingPath = new BindingPath(bindingPathText);
        var fullPath = ToLoaderPath(RawBindingPath.Append(bindingPath), _owner);
        _usesParentsDatabinding = false;
        _declaresDataSource = true;
        _dataSourceType = ViewModelPaths.GetTypeAtPath(RootDataSourceType, fullPath);
        if (IsRoot)
        {
            _bindingPath = new BindingPath("Root").Append(bindingPath);
            _rootUsesSubPath = true;
        }
        else
        {
            _bindingPath = bindingPath;
        }
    }
}