using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Reflection.Metadata;
using System.Reflection.PortableExecutable;

namespace Bannerlord.UIExtenderEx.CompiledPrefabs.Compilation;

/// <summary>
/// Compiles generated prefab C# code using bundled, internalized Roslyn compiler libraries.
/// <para>
/// Initial session compilation requires approximately two seconds for JIT warm-up and metadata table initialization,
/// after which subsequent prefab compilations take approximately 100 milliseconds per movie.
/// </para>
/// <para>
/// Bundling and internalizing Roslyn avoids dependency version collisions with game and third-party mod distributions
/// that ship varying versions of <c>System.Collections.Immutable</c> and <c>System.Reflection.Metadata</c>.
/// </para>
/// </summary>
public sealed class RoslynCompiler : ICSharpCompiler
{
    /// <summary>
    /// Manages cached Roslyn <see cref="MetadataReference"/> instances indexed by assembly file paths.
    /// <para>
    /// Encapsulated in an inner class to defer static initialization until the first compilation request,
    /// avoiding premature type loading during early JIT execution.
    /// </para>
    /// <para>
    /// Tracks file length and last write timestamp to invalidate cached references when mod assemblies are modified on disk.
    /// </para>
    /// </summary>
    private static class References
    {
        private sealed record Entry(long Length, DateTime Modified, MetadataReference Reference);

        private static readonly ConcurrentDictionary<string, Entry> Cache = new(StringComparer.OrdinalIgnoreCase);

        public static MetadataReference Get(string path)
        {
            var file = new FileInfo(path);
            if (Cache.TryGetValue(path, out var cached) && cached.Length == file.Length && cached.Modified == file.LastWriteTimeUtc)
                return cached.Reference;
            var reference = CreateReference(path);
            Cache[path] = new(file.Length, file.LastWriteTimeUtc, reference);
            return reference;
        }
    }

    public string Name => "Roslyn (bundled)";

    /// <summary>
    /// Minimal synthetic widget prefab source code designed to warm up Roslyn's parser, binder, and IL emitter.
    /// </summary>
    private const string WarmUpSource = """
                                        namespace Bannerlord.UIExtenderEx.AutoGenerated
                                        {
                                            public class WarmUpWidget : TaleWorlds.GauntletUI.BaseTypes.Widget
                                            {
                                                private TaleWorlds.GauntletUI.BaseTypes.Widget _widget_0;
                                                public WarmUpWidget(TaleWorlds.GauntletUI.UIContext context) : base(context) { }
                                                public void CreateWidgets()
                                                {
                                                    _widget_0 = new TaleWorlds.GauntletUI.BaseTypes.Widget(this.Context);
                                                    this.AddChild(_widget_0);
                                                    _widget_0.IsVisible = true;
                                                }
                                            }
                                        }
                                        """;

    public CompilationResult Compile(string assemblyName, IReadOnlyList<GeneratedSource> sources, IReadOnlyList<string> referencePaths) =>
        CompileCore(assemblyName, sources, referencePaths);

    /// <summary>
    /// Creates a Roslyn <see cref="MetadataReference"/> for the specified assembly file path.
    /// Publicizes non-framework assemblies in memory so that internal ViewModel and mixin declarations are accessible during compilation.
    /// </summary>
    private static MetadataReference CreateReference(string path)
    {
        var name = Path.GetFileNameWithoutExtension(path);
        if (IgnoresAccessChecksSource.IsFramework(name))
            return MetadataReference.CreateFromFile(path);

        try
        {
            return MetadataReference.CreateFromImage(ReferencePublicizer.Publicize(path), filePath: path);
        }
        catch (Exception e)
        {
            Trace.TraceWarning("UIExtenderEx: could not publicize '{0}', its internal types will not compile: {1}", name, e.Message);
            return MetadataReference.CreateFromFile(path);
        }
    }

    /// <summary>
    /// Configures internal Roslyn compiler options to bypass accessibility validation, allowing references to internal types.
    /// </summary>
    private static bool IgnoreAccessibility(CSharpCompilationOptions options)
    {
        try
        {
            var property = typeof(CSharpCompilationOptions).GetProperty("TopLevelBinderFlags", BindingFlags.Instance | BindingFlags.NonPublic);
            if (property is null)
                return false;
            property.SetValue(options, Enum.ToObject(property.PropertyType, 0x400000u));
            return true;
        }
        catch (Exception e)
        {
            Trace.TraceWarning("UIExtenderEx: could not make Roslyn ignore accessibility, internal mixins will not compile: {0}", e.Message);
            return false;
        }
    }

    public void WarmUp(IReadOnlyList<string> referencePaths)
    {
        // Warms up the parser, symbol binder, and IL code generator while importing assembly reference metadata.
        CompileCore("Bannerlord.UIExtenderEx.AutoGenerated.WarmUp", [new("WarmUp.gen.cs", WarmUpSource)], referencePaths);
    }

    private static CompilationResult CompileCore(string assemblyName, IReadOnlyList<GeneratedSource> sources, IReadOnlyList<string> referencePaths)
    {
        var parseOptions = new CSharpParseOptions(LanguageVersion.Latest);
        var trees = sources.Select(x => CSharpSyntaxTree.ParseText(x.Content, parseOptions, x.FileName)).ToList();
        var references = referencePaths.Select(References.Get).ToList();

        // Suppresses member accessibility diagnostics during symbol binding; the emitted assembly declares [IgnoresAccessChecksTo].
        var options = new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary, optimizationLevel: OptimizationLevel.Release, deterministic: true)
            .WithMetadataImportOptions(MetadataImportOptions.All);
        IgnoreAccessibility(options);

        var compilation = CSharpCompilation.Create(assemblyName, trees, references, options);

        using var stream = new MemoryStream();
        var result = compilation.Emit(stream);
        if (!result.Success)
        {
            var errors = result.Diagnostics
                .Where(x => x.Severity == DiagnosticSeverity.Error)
                .Select(x => x.ToString())
                .ToList();
            return CompilationResult.Failed(errors);
        }

        var image = stream.ToArray();
        return CompilationResult.Succeeded(image, ReferencedPaths(compilation, image));
    }

    /// <summary>
    /// Resolves the exact assembly reference file paths recorded in the emitted assembly's <c>AssemblyRef</c> metadata table.
    /// <para>
    /// Inspecting the emitted metadata table ensures that only assemblies strictly referenced in IL or member signatures
    /// are retained as dependencies, avoiding over-inclusive dependencies reported by namespace lookups.
    /// </para>
    /// </summary>
    private static List<string> ReferencedPaths(CSharpCompilation compilation, byte[] image)
    {
        var paths = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        foreach (var reference in compilation.References.OfType<PortableExecutableReference>())
        {
            if (reference.FilePath is { } path && compilation.GetAssemblyOrModuleSymbol(reference) is IAssemblySymbol assembly && !paths.ContainsKey(assembly.Identity.Name))
                paths[assembly.Identity.Name] = path;
        }

        using var peReader = new PEReader(ImmutableArray.Create(image));
        var metadata = peReader.GetMetadataReader();
        var referenced = new List<string>();
        foreach (var handle in metadata.AssemblyReferences)
        {
            if (paths.TryGetValue(metadata.GetString(metadata.GetAssemblyReference(handle).Name), out var path))
                referenced.Add(path);
        }
        return referenced;
    }
}