using Bannerlord.UIExtenderEx.CompiledPrefabs;
using Bannerlord.UIExtenderEx.CompiledPrefabs.Compilation;
using Bannerlord.UIExtenderEx.GauntletUI.CodeGenerator;
using Bannerlord.UIExtenderEx.GauntletUI.CodeGenerator.Runtime;
using Bannerlord.UIExtenderEx.GauntletUI.CodeGenerator.Widgets;

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;

using TaleWorlds.GauntletUI;
using TaleWorlds.GauntletUI.BaseTypes;
using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.PrefabSystem;
using TaleWorlds.Library;
using TaleWorlds.TwoDimension;

using AgreedValues = System.Collections.Generic.Dictionary<string, System.Collections.Generic.Dictionary<string, ulong>>;

namespace Bannerlord.UIExtenderEx.Tests.Oracle;

/// <summary>
/// Executes databinding verification for prefabs by synthesizing dynamic ViewModels and driving runtime movie instances.
/// <para>
/// Synthesizes a dedicated <see cref="ViewModel"/> matching the prefab's declared bindings via <see cref="ViewModelSynthesizer"/>,
/// then loads three parallel movies using <see cref="GauntletMovie.Load"/>: an interpreted XML movie, a compiled prefab movie,
/// and a second XML movie serving as a baseline control. Applies identical mutations across all three graphs, verifying that widget trees,
/// ViewModel call logs, and assertion diagnostics match between the compiled engine and the XML baseline while filtering out baseline variance.
/// </para>
/// <para>
/// Drives verification through standard lifecycle stages: movie initialization, scalar property mutations across multiple passes,
/// child ViewModel replacements, list modifications (insertions, deletions, and clear operations), widget command invocations with diverse parameter types,
/// and movie release teardown to verify subscriber detachment parity.
/// </para>
/// </summary>
public sealed class BindingLoaderOracle
{
    private const string Namespace = "Bannerlord.UIExtenderEx.AutoGenerated.BindingOracle";
    private const int MaxDifferences = 200;
    private const int MaxDetailedChecks = 8;

    private static int _prefabs;

    private readonly WidgetFactory _widgetFactory;
    private readonly SpriteData _spriteData;
    private readonly BrushFactory _brushFactory;
    private readonly Func<UIContext> _newContext;
    private UIContext _context;
    private readonly List<string> _references;
    private readonly string _workDirectory;
    private readonly OracleCompiler _compiler = new();
    private readonly bool _objectTyped;

    /// <param name="objectTyped">Configures synthesized ViewModels to declare loosely typed <see cref="object"/> properties to test fallback reflection paths.</param>
    public BindingLoaderOracle(WidgetFactory widgetFactory, SpriteData spriteData, BrushFactory brushFactory, UIContext context, IEnumerable<Assembly> widgetAssemblies, bool objectTyped = false)
        : this(widgetFactory, spriteData, brushFactory, () => context, widgetAssemblies, objectTyped) { }

    /// <param name="newContext">
    /// Supplies a distinct <see cref="UIContext"/> per prefab evaluation, isolating event manager registrations across test runs.
    /// </param>
    /// <param name="objectTyped">Configures synthesized ViewModels to declare loosely typed <see cref="object"/> properties to test fallback reflection paths.</param>
    public BindingLoaderOracle(WidgetFactory widgetFactory, SpriteData spriteData, BrushFactory brushFactory, Func<UIContext> newContext, IEnumerable<Assembly> widgetAssemblies, bool objectTyped = false)
    {
        _objectTyped = objectTyped;
        _widgetFactory = widgetFactory;
        _spriteData = spriteData;
        _brushFactory = brushFactory;
        _newContext = () => WithTheLayersNavigation(newContext());
        _context = _newContext();
        var seeds = new HashSet<Assembly>(widgetAssemblies)
        {
            typeof(ViewModel).Assembly, typeof(Widget).Assembly, typeof(WidgetPrefab).Assembly, typeof(SpriteData).Assembly,
            typeof(PrefabReferenceSet).Assembly, typeof(GauntletMovie).Assembly, typeof(DynamicMember).Assembly, typeof(SynthValues).Assembly,
        };
        _references = PrefabReferenceSet.ToPaths(PrefabReferenceSet.Select(seeds));
        _workDirectory = Path.Combine(Path.GetTempPath(), "UIExtenderEx-oracle", "viewmodels-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(_workDirectory);
        // Initializes gamepad navigation manager to prevent null-reference exceptions in EventManager when detaching widgets.
        TaleWorlds.GauntletUI.GamepadNavigation.GauntletGamepadNavigationManager.Initialize();
        // Resolves dynamically compiled ViewModel assemblies when compiled prefabs bind type references by name.
        AppDomain.CurrentDomain.AssemblyResolve += (_, args) =>
            _compiler.Assemblies.FirstOrDefault(x => string.Equals(x.FullName, args.Name, StringComparison.Ordinal));
    }

    /// <summary>
    /// Configures the <see cref="UIContext"/> with an active navigation context to ensure gamepad scopes unsubscribe correctly when widgets detach.
    /// </summary>
    private static UIContext WithTheLayersNavigation(UIContext context)
    {
        if (context.GamepadNavigation is EmptyGamepadNavigationContext)
            context.InitializeGamepadNavigation(new GauntletGamepadNavigationContext(_ => false, () => 0, () => true));
        return context;
    }

    /// <summary>
    /// Finalizes the current context and advances to a fresh <see cref="UIContext"/> instance for the next prefab execution.
    /// </summary>
    private void NextContext()
    {
        var next = _newContext();
        if (!ReferenceEquals(next, _context))
            _context.OnFinalize();
        _context = next;
    }

    private sealed class Case
    {
        public Case(string prefab) => Prefab = prefab;

        public string Prefab { get; }
        public string Namespace { get; } = $"{BindingLoaderOracle.Namespace}.P{System.Threading.Interlocked.Increment(ref _prefabs)}";
        public ViewModelSynthesizer? Synthesizer { get; set; }
        public string? ViewModelSource { get; set; }
        public Type? ViewModelType { get; set; }
        public List<GeneratedSource> PrefabSources { get; } = [];
        public Assembly? PrefabAssembly { get; set; }
    }

    /// <summary>
    /// Validates and serves dynamically compiled prefab variants belonging exclusively to the oracle's test namespace.
    /// </summary>
    private sealed class OracleRuntime : Bannerlord.UIExtenderEx.Runtimes.IPrefabRuntime
    {
        public static readonly OracleRuntime Instance = new();

        public bool TryServe(WidgetFactory widgetFactory, string movieName, IViewModel? dataSource) =>
            dataSource?.GetType().Namespace?.StartsWith(Namespace, StringComparison.Ordinal) == true;

        public bool IsOwnVariant(Assembly variantAssembly) => variantAssembly.GetName().Name?.StartsWith(Namespace, StringComparison.Ordinal) == true;
    }

    public List<OracleResult> Run(IReadOnlyList<string> prefabNames, int batchSize = 24)
    {
        Bannerlord.UIExtenderEx.Runtimes.PrefabRuntimes.Register(OracleRuntime.Instance);
        var previousHost = DynamicMember.Host;
        // Installs the runtime member accessor host to resolve fast reflection dispatches during evaluation.
        DynamicMember.Host = new DynamicMemberHost();
        try
        {
            var results = new List<OracleResult>();
            for (var start = 0; start < prefabNames.Count; start += batchSize)
            {
                var stopwatch = System.Diagnostics.Stopwatch.StartNew();
                results.AddRange(RunBatch([.. prefabNames.Skip(start).Take(batchSize)]));
                NUnit.Framework.TestContext.Progress.WriteLine($"binding oracle: {Math.Min(start + batchSize, prefabNames.Count)}/{prefabNames.Count} in {stopwatch.Elapsed.TotalSeconds:F1} s");
            }
            if (MemoryLog)
                LogRetention();
            return results;
        }
        finally
        {
            DynamicMember.Host = previousHost;
        }
    }

    private static readonly bool MemoryLog = Environment.GetEnvironmentVariable("UIEXTENDEREX_ORACLE_MEMORY") == "1";

    /// <summary>
    /// Emits memory diagnostics and loaded assembly statistics when <c>UIEXTENDEREX_ORACLE_MEMORY=1</c> is configured.
    /// </summary>
    private static void LogMemory(string where)
    {
        if (!MemoryLog)
            return;
        var live = GC.GetTotalMemory(forceFullCollection: true) / (1024 * 1024);
        using var process = System.Diagnostics.Process.GetCurrentProcess();
        NUnit.Framework.TestContext.Progress.WriteLine(
            $"binding oracle memory {where}: live {live} MB, private {process.PrivateMemorySize64 / (1024 * 1024)} MB, " +
            $"working set {process.WorkingSet64 / (1024 * 1024)} MB, peak {process.PeakWorkingSet64 / (1024 * 1024)} MB, " +
            $"{AppDomain.CurrentDomain.GetAssemblies().Length} assemblies ({AppDomain.CurrentDomain.GetAssemblies().Count(x => x.IsDynamic || string.IsNullOrEmpty(x.Location))} without a file); " +
            $"still alive: {StillAlive()}");
    }

    private List<OracleResult> RunBatch(IReadOnlyList<string> prefabNames)
    {
        LogMemory("before the batch");
        var results = new List<OracleResult>();

        // 1. Synthesizes a ViewModel per prefab into a shared assembly for subsequent prefab compilation.
        var cases = new List<Case>();
        foreach (var prefab in prefabNames)
        {
            OracleMemoryGuard.Check($"synthesizing a ViewModel for '{prefab}'");
            var item = new Case(prefab);
            try
            {
                item.Synthesizer = new ViewModelSynthesizer(_widgetFactory, _objectTyped);
                item.Synthesizer.Collect(prefab);
                item.ViewModelSource = item.Synthesizer.Emit(item.Namespace);
                cases.Add(item);
            }
            catch (Exception e)
            {
                results.Add(new(prefab, OracleOutcome.XmlThrows, [], "the prefab cannot be read: " + LoaderOracle.Describe(e), 0, 0));
            }
        }

        var withViewModels = new List<Case>();
        foreach (var (group, assembly, errors) in _compiler.Compile($"{Namespace}.ViewModels", cases,
                     x => [new GeneratedSource(x.Namespace + ".ViewModels.cs", x.ViewModelSource!)], _references, SaveAndLoad))
        {
            foreach (var item in group)
            {
                if (assembly?.GetType($"{item.Namespace}.S0") is { } type)
                {
                    item.ViewModelType = type;
                    withViewModels.Add(item);
                }
                else
                {
                    results.Add(new(item.Prefab, OracleOutcome.HarnessFailed, [], "synthesized ViewModel: " + string.Join(" | ", errors.Take(3)), 0, 0));
                }
            }
        }
        LogMemory("after the ViewModels compiled");
        var references = _references.Concat(_compiler.Assemblies.Where(x => !string.IsNullOrEmpty(x.Location)).Select(x => x.Location)).Distinct().ToList();

        // 2. Generates C# code for each prefab against the synthesized ViewModels in bounded compilation batches.
        var generated = new List<Case>();
        long generatedSize = 0;
        foreach (var item in withViewModels)
        {
            try
            {
                using var lease = WidgetFactoryLookup.PrefabLease.Begin(_widgetFactory);
                var context = new PrefabCodeGenerator(item.Namespace, _widgetFactory, _spriteData, _brushFactory);
                context.AddMovie(item.Prefab, item.ViewModelType!.FullName, item.ViewModelType);
                item.PrefabSources.AddRange(context.GenerateInMemory().Select(x => new GeneratedSource(item.Namespace + "." + x.Key, x.Value)));
                if (Environment.GetEnvironmentVariable("UIEXTENDEREX_ORACLE_DUMP_SOURCES") == "1")
                {
                    var directory = Path.Combine(_workDirectory, item.Prefab);
                    Directory.CreateDirectory(directory);
                    File.WriteAllText(Path.Combine(directory, "ViewModels.cs"), item.ViewModelSource);
                    foreach (var source in item.PrefabSources)
                        File.WriteAllText(Path.Combine(directory, source.FileName), source.Content);
                    NUnit.Framework.TestContext.Progress.WriteLine($"binding oracle: {item.Prefab} sources in {directory}");
                }
                var size = item.PrefabSources.Sum(x => (long) x.Content.Length);
                if (MemoryLog)
                    NUnit.Framework.TestContext.Progress.WriteLine($"binding oracle source {item.Prefab}: {size / 1024} KB in {item.PrefabSources.Count} files");
                generated.Add(item);
                generatedSize += size;
            }
            catch (Exception e)
            {
                // Verifies whether interpreted XML execution succeeds to distinguish generator defects from inherent prefab defects.
                results.Add(OracleDeclines.Classify(item.Prefab, e, () => OpenFromXml(item)));
            }
            if (generatedSize >= MaxCompiledSource)
            {
                CompileAndDrive(generated, references, results);
                generated.Clear();
                generatedSize = 0;
            }
        }
        CompileAndDrive(generated, references, results);
        return results;
    }

    /// <summary>
    /// Defines the character limit for batched prefab source code compilations to constrain Roslyn memory consumption.
    /// </summary>
    private const long MaxCompiledSource = 16 * 1024 * 1024;

    /// <summary>Compiles prefab source batches, registers factory creators with <see cref="GeneratedPrefabContext"/>, and drives verification.</summary>
    private void CompileAndDrive(List<Case> generated, List<string> references, List<OracleResult> results)
    {
        if (generated.Count == 0)
            return;
        LogMemory("after the prefabs generated");
        foreach (var (group, assembly, errors) in _compiler.Compile($"{Namespace}.Prefabs", generated, x => x.PrefabSources, references))
        {
            if (assembly is null)
            {
                results.AddRange(group.Select(x => new OracleResult(x.Prefab, OracleOutcome.NotCompiled, [], string.Join(Environment.NewLine, errors.Take(5)), 0, 0)));
                continue;
            }
            LogMemory("after the prefabs compiled");
            // Registers generated widget classes with WidgetInfo using creator instances bound to the target assembly namespace.
            _compiler.Environment.CreateCreator(assembly);
            foreach (var item in group)
            {
                OracleMemoryGuard.Check($"driving '{item.Prefab}'");
                NextContext();
                item.PrefabAssembly = assembly;
                var creatorType = assembly.GetType($"{item.Namespace}.{PrefabCodeGenerator.CreatorClassName}", throwOnError: true)!;
                var collect = creatorType.GetMethod(PrefabCodeGenerator.CollectMethodName, [typeof(GeneratedPrefabContext)])!;
                collect.Invoke(Activator.CreateInstance(creatorType), [_widgetFactory.GeneratedPrefabContext]);
                var watch = System.Diagnostics.Stopwatch.StartNew();
                var driven = Drive(item);
                results.Add(driven);
                NUnit.Framework.TestContext.Progress.WriteLine($"binding oracle: {item.Prefab} {driven.Outcome} in {watch.Elapsed.TotalSeconds:F1} s");
                LogMemory($"after {item.Prefab}");
                CollectAfterLargePrefab();
            }
        }
        // Releases generated source buffers after driving verification to free managed memory.
        foreach (var item in generated)
            item.PrefabSources.Clear();
    }

    /// <summary>Tracks the retained managed heap byte count following the most recent garbage collection cycle.</summary>
    private long _heldAfterCollect;

    private const long CollectAfterGrowth = 256 * 1024 * 1024;

    /// <summary>
    /// Triggers garbage collection when heap growth exceeds <see cref="CollectAfterGrowth"/> to stabilize memory between heavy prefabs.
    /// </summary>
    private void CollectAfterLargePrefab()
    {
        if (GC.GetTotalMemory(forceFullCollection: false) - _heldAfterCollect < CollectAfterGrowth)
            return;
        var watch = System.Diagnostics.Stopwatch.StartNew();
        GC.Collect();
        GC.WaitForPendingFinalizers();
        GC.Collect();
        _heldAfterCollect = GC.GetTotalMemory(forceFullCollection: false);
        NUnit.Framework.TestContext.Progress.WriteLine($"binding oracle: collected in {watch.Elapsed.TotalMilliseconds:F0} ms, {_heldAfterCollect / (1024 * 1024)} MB held");
    }

    /// <summary>Attempts to load and release the movie using the interpreted XML engine, returning diagnostic error details if loading fails.</summary>
    private string? OpenFromXml(Case item)
    {
        var dataSource = (ViewModel) Activator.CreateInstance(item.ViewModelType!, new SynthValues.Log(), "Root", 1)!;
        IGauntletMovie? movie = null;
        try
        {
            movie = GauntletMovie.Load(_context, _widgetFactory, item.Prefab, dataSource, doNotUseGeneratedPrefabs: true, hotReloadEnabled: false);
            return null;
        }
        catch (Exception e)
        {
            return LoaderOracle.Describe(e);
        }
        finally
        {
            try
            {
                if (movie is { IsReleased: false })
                    movie.Release();
            }
            catch (Exception) { /* Suppresses teardown failures during test diagnostic classification. */ }
        }
    }

    private Assembly SaveAndLoad(byte[] image, string name)
    {
        var path = Path.Combine(_workDirectory, name + ".dll");
        File.WriteAllBytes(path, image);
        return Assembly.LoadFrom(path);
    }

    // --- driving one prefab ---------------------------------------------------------------------------------------------

    /// <summary>Holds the runtime execution state and movies for XML, compiled, and XML control instances.</summary>
    private sealed class Run3
    {
        public readonly SynthValues.Log[] Logs = [new(), new(), new()];
        public readonly ViewModel[] ViewModels = new ViewModel[3];
        public readonly IGauntletMovie?[] Movies = new IGauntletMovie?[3];
        public readonly List<string>[] Asserts = [[], [], []];
        public readonly List<string> Differences = [];
        /// <summary>Tracks reported widget hierarchy paths to ensure persistent differences are recorded only once.</summary>
        public readonly HashSet<string> Reported = new(StringComparer.Ordinal);

        /// <summary>
        /// Stores widgets that intentionally diverge due to recognized runtime design differences documented in <see cref="IntendedDeviations"/>.
        /// </summary>
        public readonly List<Widget> Diverged = [];

        /// <summary>Tracks the log read offset for each test movie to support incremental comparison across evaluation steps.</summary>
        public readonly int[] LogMarks = new int[3];
        public int ComparedAsserts;
        public int Checks;

        /// <summary>Maps ViewModel properties bound to widget properties that TaleWorlds engine resets upon widget detachment.</summary>
        public Dictionary<string, HashSet<string>> ResetOnRemoval = new(StringComparer.Ordinal);

        /// <summary>Indicates whether an intentional deviation occurred during the step, bypassing ViewModel invocation comparisons.</summary>
        public bool IntendedSinceCheck;
        public Func<string, string> CompiledAsVisible = x => x;

        /// <summary>Tracks XML widget instances rebuilt due to known interpreted runtime list reset behavior.</summary>
        public readonly List<Widget> RebuiltSinceCheck = [];

        /// <summary>
        /// Records element count offsets in widget internal tracking collections caused by redundant XML list reconstructions.
        /// </summary>
        public readonly Dictionary<(Widget Widget, string Field), int> RebuildRecords = [];

        /// <summary>Accumulates elapsed execution duration by operation category.</summary>
        public readonly Dictionary<string, TimeSpan> Spent = new(StringComparer.Ordinal);

        public T Timed<T>(string what, Func<T> action)
        {
            var watch = System.Diagnostics.Stopwatch.StartNew();
            try
            {
                return action();
            }
            finally
            {
                Spent[what] = (Spent.TryGetValue(what, out var spent) ? spent : TimeSpan.Zero) + watch.Elapsed;
            }
        }

        public void Timed(string what, Action action) => Timed<object?>(what, () =>
        {
            action();
            return null;
        });

        /// <summary>Formats elapsed durations exceeding threshold limits and resets the timing accumulators.</summary>
        public string TakeSpent()
        {
            var text = string.Join(", ", Spent.Where(x => x.Value.TotalSeconds >= 0.1).OrderByDescending(x => x.Value)
                .Select(x => $"{x.Key} {x.Value.TotalSeconds:F1}s"));
            Spent.Clear();
            return text.Length == 0 ? "" : $" ({text})";
        }
    }

    private OracleResult Drive(Case item)
    {
        var run = new Run3 { ResetOnRemoval = item.Synthesizer!.BoundToResetOnRemoval };
        if (item.PrefabAssembly is { } prefabAssembly)
            run.CompiledAsVisible = x => _compiler.AsVisible(x, prefabAssembly);
        var type = item.ViewModelType!;
        for (var side = 0; side < 3; side++)
            run.ViewModels[side] = (ViewModel) Activator.CreateInstance(type, run.Logs[side], "Root", 1)!;

        var failures = new string?[3];
        for (var side = 0; side < 3; side++)
        {
            var captured = side;
            failures[side] = Apply(run, side, () => run.Movies[captured] = GauntletMovie.Load(_context, _widgetFactory, item.Prefab, run.ViewModels[captured],
                doNotUseGeneratedPrefabs: captured != 1, hotReloadEnabled: false));
        }
        try
        {
            if (failures[0] is not null)
                return new(item.Prefab, OracleOutcome.XmlThrows, [], failures[0], run.Asserts[0].Count, 0);
            if (failures[1] is not null)
                return new(item.Prefab, OracleOutcome.CompiledThrows, [], "opening: " + failures[1], run.Asserts[0].Count, run.Asserts[1].Count);
            if (run.Movies[1] is GauntletMovie)
                return new(item.Prefab, OracleOutcome.CompiledThrows, [], "GauntletMovie.Load took the XML path: the compiled variant was not found", 0, 0);

            if (Environment.GetEnvironmentVariable("UIEXTENDEREX_ORACLE_DUMP_VIEWS") == "1" && run.Movies[0] is GauntletMovie xmlMovie)
                NUnit.Framework.TestContext.Progress.WriteLine(DumpViews(xmlMovie.RootView, 0));
            var phases = new System.Text.StringBuilder();
            var watch = System.Diagnostics.Stopwatch.StartNew();
            void Phase(string name, Action action)
            {
                var checks = run.Checks;
                OracleMemoryGuard.At($"'{item.Prefab}', {name}");
                LogMemory($"'{item.Prefab}' before {name}");
                watch.Restart();
                run.Spent.Clear();
                action();
                LogMemory($"'{item.Prefab}' after {name}");
                phases.Append($" {name} {watch.Elapsed.TotalSeconds:F1}s/{run.Checks - checks}{run.TakeSpent()}");
            }
            Phase("open", () => Check(run, "opening", deep: true));
            Phase("properties", () => ChangeProperties(run));
            Phase("children", () => ReplaceChildren(run));
            Phase("lists", () => ChangeLists(run));
            Phase("commands", () => FireCommands(run, item.Synthesizer!.EventNames));
            Phase("release", () => Release(run));
            NUnit.Framework.TestContext.Progress.WriteLine($"binding oracle phases: {item.Prefab}:{phases}");

            var outcome = run.Differences.Count == 0 ? OracleOutcome.Match : OracleOutcome.Differs;
            return new(item.Prefab, outcome, [.. run.Differences.Take(MaxDifferences)], null, run.Asserts[0].Count, run.Asserts[1].Count);
        }
        catch (Exception e)
        {
            return new(item.Prefab, OracleOutcome.CompiledThrows, [.. run.Differences.Take(MaxDifferences)], "driving: " + LoaderOracle.Describe(e), run.Asserts[0].Count, run.Asserts[1].Count);
        }
        finally
        {
            foreach (var movie in run.Movies)
            {
                try
                {
                    if (movie is { IsReleased: false })
                        movie.Release();
                }
                catch (Exception) { /* Suppresses release teardown exceptions during final disposal. */ }
            }
            if (MemoryLog)
                Track(item.Prefab, run);
        }
    }

    private static readonly List<(string Prefab, string What, WeakReference Target)> Tracked = [];

    /// <summary>Maintains weak references to completed movie instances and widgets to monitor memory reclamation.</summary>
    private static void Track(string prefab, Run3 run)
    {
        for (var side = 0; side < 3; side++)
        {
            if (run.Movies[side]?.RootWidget is { } root)
                Tracked.Add((prefab, SideNames[side] + " tree", new WeakReference(root)));
            if (run.Movies[side] is { } movie)
                Tracked.Add((prefab, SideNames[side] + " movie", new WeakReference(movie)));
            Tracked.Add((prefab, SideNames[side] + " ViewModel", new WeakReference(run.ViewModels[side])));
        }
        Tracked.Add((prefab, "run", new WeakReference(run)));
    }

    /// <summary>Inspects and logs GC reference retention roots for widgets remaining reachable after batch execution.</summary>
    private void LogRetention()
    {
        GC.Collect();
        GC.WaitForPendingFinalizers();
        GC.Collect();
        var first = Tracked.FirstOrDefault().Prefab;
        var assemblies = AppDomain.CurrentDomain.GetAssemblies()
            .Where(x => x.GetName().Name is { } name && (name.StartsWith("TaleWorlds.", StringComparison.Ordinal) || name.StartsWith("Bannerlord.", StringComparison.Ordinal)))
            .ToList();
        foreach (var (prefab, what, reference) in Tracked.Where(x => x.Prefab == first && x.What.EndsWith(" tree", StringComparison.Ordinal)))
        {
            if (reference.Target is not { } target)
            {
                NUnit.Framework.TestContext.Progress.WriteLine($"binding oracle retention: {prefab} {what} was collected");
                continue;
            }
            var path = OracleRetention.PathTo(target, assemblies,
                [("the oracle's UIContext", _context), ("the oracle's WidgetFactory", _widgetFactory), ("the oracle's BrushFactory", _brushFactory), ("the oracle", this)]);
            NUnit.Framework.TestContext.Progress.WriteLine($"binding oracle retention: {prefab} {what} is held by{Environment.NewLine}    {path ?? "nothing found from the roots searched"}");
        }
    }

    private static string StillAlive()
    {
        var alive = Tracked.Where(x => x.Target.IsAlive).GroupBy(x => x.Prefab).Select(x => $"{x.Key} [{string.Join(", ", x.Select(y => y.What))}]").ToList();
        return alive.Count == 0 ? "nothing of the prefabs driven before" : string.Join("; ", alive);
    }

    private static readonly string[] SideNames = ["xml", "compiled", "control"];

    /// <summary>Executes an action on a specific movie instance, capturing thrown exceptions and diagnostic assertion messages.</summary>
    private static string? Apply(Run3 run, int side, Action action)
    {
        using (run.Timed("asserts", () => LoaderOracle.RecordAsserts(run.Asserts[side])))
        {
            try
            {
                run.Timed(SideNames[side], action);
                return null;
            }
            catch (Exception e)
            {
                // Normalizes exception details by capturing unwrapped innermost messages across XML and compiled stacks.
                var inner = e;
                while (inner is TargetInvocationException { InnerException: { } wrapped })
                    inner = wrapped;
                return $"{inner.GetType().Name}: {inner.Message}";
            }
        }
    }

    /// <summary>Applies an operation across all three movie variants, recording discrepancies when the compiled movie diverges from XML baseline parity.</summary>
    private static void ApplyToAll(Run3 run, string label, Action<int> action)
    {
        var failures = new string?[3];
        for (var side = 0; side < 3; side++)
        {
            var captured = side;
            OracleMemoryGuard.At($"{label}, {(side == 1 ? "compiled" : side == 0 ? "XML" : "the XML control")}");
            failures[side] = Apply(run, side, () => action(captured));
        }
        if (failures[0] == failures[2] && failures[0] != failures[1] && !IsParsedAlignmentName(failures[0], failures[1]) && !IsCastNumber(failures[0], failures[1])
            && !IsNeverFittingWriteBack(failures[0], failures[1]))
            Record(run, $"{label}: XML {failures[0] ?? "succeeds"}, compiled {failures[1] ?? "succeeds"}");
    }

    private static readonly System.Text.RegularExpressions.Regex ConversionRejected = new(
        @"^ArgumentException: Object of type '(?<announced>[^']+)' cannot be converted to type '(?<property>[^']+)'\.$");

    /// <summary>
    /// Determines whether an exception matches the recognized intentional deviation where compiled write-backs safely drop incompatible types.
    /// </summary>
    private static bool IsNeverFittingWriteBack(string? xml, string? compiled)
    {
        if (compiled is not null || xml is null || ConversionRejected.Match(xml) is not { Success: true } match)
            return false;
        if (FindType(match.Groups["announced"].Value) is not { } announced || FindType(match.Groups["property"].Value) is not { } property)
            return false;
        if (announced == typeof(string) || NumberRejected.IsMatch(xml))
            return false;
        return !property.IsAssignableFrom(announced) && (property.IsValueType || property.IsSealed) && !property.IsInterface;
    }

    private static readonly Dictionary<string, Type?> TypesByName = new(StringComparer.Ordinal);

    private static Type? FindType(string fullName)
    {
        lock (TypesByName)
        {
            if (!TypesByName.TryGetValue(fullName, out var type))
                TypesByName[fullName] = type = AppDomain.CurrentDomain.GetAssemblies().Select(x => x.GetType(fullName, false)).FirstOrDefault(x => x is not null);
            return type;
        }
    }

    private const string NumberType = @"System\.(?:S?Byte|U?Int16|U?Int32|U?Int64|Single|Double)";

    private static readonly System.Text.RegularExpressions.Regex NumberRejected = new(
        $@"^ArgumentException: Object of type '{NumberType}' cannot be converted to type '{NumberType}'\.$");

    /// <summary>Determines whether a numeric conversion mismatch matches the intentional deviation where compiled write-backs cast numeric values.</summary>
    private static bool IsCastNumber(string? xml, string? compiled) =>
        compiled is null && xml is not null && NumberRejected.IsMatch(xml);

    private static readonly System.Text.RegularExpressions.Regex AlignmentNameRejected = new(
        @"^ArgumentException: Object of type 'System\.String' cannot be converted to type 'TaleWorlds\.GauntletUI\.(?:Horizontal|Vertical|TextHorizontal)Alignment'\.$");

    /// <summary>Determines whether an alignment string conversion matches the intentional deviation where compiled write-backs parse enum names.</summary>
    private static bool IsParsedAlignmentName(string? xml, string? compiled) =>
        compiled is null && xml is not null && AlignmentNameRejected.IsMatch(xml);

    private static void Record(Run3 run, string difference)
    {
        if (run.Differences.Count < MaxDifferences)
            run.Differences.Add(difference);
    }

    /// <summary>
    /// Documents documented behavioral deviations where compiled prefabs intentionally differ from the interpreted XML engine.
    /// </summary>
    public static readonly IReadOnlyDictionary<string, string> IntendedDeviations = new Dictionary<string, string>(StringComparer.Ordinal)
    {
        ["stale child ViewModel"] =
            "A child ViewModel replaced by its owner is shown by every widget bound to it. GauntletView refreshes only the " +
            "views directly under a view that has the owner, so a widget that reaches the child from a sibling scope " +
            "(DataSource=\"{..\\Visual}\" under \"{Hint}\") keeps showing the old one in XML. The compiled prefab keeps one " +
            "data source per path and updates them all, which is the correct behaviour, and kept on purpose.",
        ["alignment name written back"] =
            "From v1.1.0 an alignment announces a change as its name, and XML's SetPropertyValue throws handing that string " +
            "to an enum property. The analyzer makes such a binding a build error (UIX0025), so the compiled prefab parses " +
            "the name back into the enum and assigns it. Both sides hold the same values afterwards; only the throw differs.",
        ["value the property can never take not written back"] =
            "ViewModel.SetPropertyValue hands a property what the widget announced as it is, so a Brush a BrushWidget " +
            "announces, bound to a string property, throws on every change in XML, out of whatever set the brush; neither " +
            "side's value changes. The analyzer makes such a binding a build error from the announcements the GUI package " +
            "records (UIX0025), so the compiled write-back drops the value. Told apart by XML's ArgumentException naming a " +
            "property type that is sealed or a value type and cannot hold the announced one, where the compiled step " +
            "succeeds; the values are still compared.",
        ["number cast written back"] =
            "ViewModel.SetPropertyValue hands a property the number the widget announced as it is, and reflection does not " +
            "narrow, so a float SuggestedWidth written back into an int property throws on every change in XML. The analyzer " +
            "makes such a binding a build error (UIX0025), so the compiled prefab casts the number, unchecked, as C# casts, " +
            "and the binding works both ways. Told apart by XML's ArgumentException naming two number types where the " +
            "compiled step succeeds; values a cast changes are still compared.",
        ["reset written back on removal"] =
            "When a widget leaves the tree the game resets its GamepadNavigationIndex to -1, UsedNavigationMovements to None " +
            "and IsUsingNavigation to false (EventManager.OnWidgetDisconnectedFromRoot). XML's write-back is still attached " +
            "at that moment - GauntletMovie.Release takes the views off their ViewModels only, and RemoveItemFromList removes " +
            "an item before it clears its handlers - so a two-way binding of one of them writes the reset value into a " +
            "ViewModel whose screen has closed or whose item is gone. The compiled prefab unsubscribes first and writes " +
            "nothing, which is correct. Kept on purpose, without an analyzer rule: telling which properties the game resets " +
            "would take a hand-written game fact, and no installed prefab binds them. Told apart by the compiled step's " +
            "ViewModel calls being XML's without the writes of those values into properties bound to those widget properties.",
        ["list rebuilt through {..}"] =
            "Replacing a child ViewModel makes GauntletView refresh every view under the one bound to it, and refreshing a " +
            "list view resets it and builds every item again - also a list reached back out of the child through {..}, " +
            "which has not changed. The compiled prefab keeps one data source per path and leaves such a list's items as " +
            "they are. XML's items are new widgets (their visual state and animations start over), and the items it throws " +
            "away leave their gamepad navigation scopes subscribed to every ancestor. Kept on purpose, without an analyzer " +
            "rule: neither side shows a value the other does not, and the game's own prefabs use the construct. Told apart " +
            "by the XML item being a new widget over the same item ViewModel while the compiled one is the same widget, and " +
            "by leaked subscribers counted apart (WidgetSnapshot.RemovedSubscribers), of which XML may have more.",
        ["list rebuilt through a name prefix"] =
            "GauntletView.OnPropertyChanged picks the child views to refresh with BindingPath.IsRelatedWithPathAsString, a " +
            "plain StartsWith on the paths, so replacing Player refreshes the view at Root\\PlayerActions as well " +
            "(Lobby.Friends), and a list view that is refreshed throws its items away and builds them again. The compiled " +
            "prefab refreshes what was replaced and leaves the list as it is. Kept on purpose, without an analyzer rule, " +
            "as \"list rebuilt through {..}\" is: neither side shows a value the other does not, and the game's own " +
            "prefabs have the pair. Told apart as that one is, by the XML item being a new widget over the same item " +
            "ViewModel; a widget above it keeping a record of the items added and removed (ContextMenuBrushWidget) counts " +
            "the rebuild, and may differ by that many entries from then on.",
        ["indexed item followed"] =
            @"A DataSource that steps into a list by index ({Perks\0\CandidatePerks}) shows the item now at that index. " +
            "XML resolves such a path only when the list is replaced: a list changed in place leaves the widget on the item " +
            "that was there, or on one no longer in the list. The compiled prefab follows the list, which is correct, and the " +
            "analyzer makes the construct an error (UIX0028). Told apart by the XML view holding another data source than " +
            "the one its own path leads to now.",
    };

    private static readonly FieldInfo? BindingListOfView = typeof(GauntletView).GetField("_bindingList", BindingFlags.Instance | BindingFlags.NonPublic);
    private static readonly FieldInfo? OwnPathOfView = typeof(GauntletView).GetField("_viewModelPath", BindingFlags.Instance | BindingFlags.NonPublic);
    private static readonly FieldInfo? ChildrenOfView = typeof(GauntletView).GetField("_children", BindingFlags.Instance | BindingFlags.NonPublic);
    private static readonly MethodInfo? MovieViewModelAtPath = typeof(GauntletMovie).GetMethod("GetViewModelAtPath", BindingFlags.Instance | BindingFlags.NonPublic, null, [typeof(BindingPath), typeof(bool)], null);

    /// <summary>
    /// The XML widgets left on an item a list no longer has there: <see cref="IntendedDeviations"/>' "indexed item followed".
    /// A view whose own DataSource steps into a list by index, holding another data source than its path leads to now -
    /// by XML's own measure, so nothing compiled decides it. A list item's view is not one: its path is its index alone,
    /// which XML keeps current.
    /// </summary>
    private static List<Widget> StaleIndexedInXml(Run3 run)
    {
        var stale = new List<Widget>();
        if (run.Movies[0] is not GauntletMovie movie || ChildrenOfView is null || OwnPathOfView is null || MovieViewModelAtPath is null)
            return stale;
        var pending = new Stack<GauntletView>();
        pending.Push(movie.RootView);
        while (pending.Count > 0)
        {
            var view = pending.Pop();
            if (OwnPathOfView.GetValue(view) is BindingPath { Nodes.Length: > 1 } own && own.Nodes.Any(x => x.Length > 0 && char.IsDigit(x[0])))
            {
                var held = ViewModelOfView?.GetValue(view) ?? BindingListOfView?.GetValue(view);
                var current = MovieViewModelAtPath.Invoke(movie, [view.ViewModelPath, view.ItemTemplateUsageWithData?.ItemTemplateUsage != null]);
                if (!ReferenceEquals(held, current))
                {
                    stale.Add(view.Target);
                    continue;
                }
            }
            foreach (GauntletView child in (IEnumerable) ChildrenOfView.GetValue(view)!)
                pending.Push(child);
        }
        return stale;
    }

    private static readonly System.Text.RegularExpressions.Regex CountValue = new(@"^count (\d+)$");

    /// <summary>
    /// Identifies tracking collection count discrepancies caused by redundant widget rebuilding in the interpreted XML engine.
    /// </summary>
    private static bool IsRebuildRecord(Run3 run, string key, string? xml, string? compiled)
    {
        var colon = key.IndexOf(':');
        if (colon < 0 || run.Movies[0]?.RootWidget is not { } xmlRoot)
            return false;
        var bracket = key.IndexOf('[', colon);
        var field = bracket < 0 ? key.Substring(colon + 1) : key.Substring(colon + 1, bracket - colon - 1);
        if (WidgetAt(xmlRoot, key.Substring(0, colon)) is not { } widget)
            return false;
        var recorded = run.RebuildRecords.TryGetValue((widget, field), out var offset);
        // Validates indexed entries belonging to collections inflated by XML widget rebuilds.
        if (bracket >= 0)
            return recorded;
        if (xml is null || compiled is null || CountValue.Match(xml) is not { Success: true } x || CountValue.Match(compiled) is not { Success: true } c)
            return false;
        var more = int.Parse(x.Groups[1].Value, System.Globalization.CultureInfo.InvariantCulture) - int.Parse(c.Groups[1].Value, System.Globalization.CultureInfo.InvariantCulture);
        if (recorded)
            return more == offset;
        if (more <= 0 || !run.RebuiltSinceCheck.Any(item => IsAbove(widget, item)))
            return false;
        run.RebuildRecords[(widget, field)] = more;
        return true;
    }

    private static bool IsAbove(Widget ancestor, Widget widget)
    {
        for (var parent = widget.ParentWidget; parent is not null; parent = parent.ParentWidget)
        {
            if (parent == ancestor)
                return true;
        }
        return false;
    }

    /// <summary>Marks XML widgets that retain outdated indexed items as intentionally diverged from compiled instances.</summary>
    private static void MarkStaleIndexed(Run3 run)
    {
        foreach (var widget in run.Timed("stale indexed", () => StaleIndexedInXml(run)))
        {
            if (!run.Diverged.Contains(widget))
            {
                run.Diverged.Add(widget);
                run.IntendedSinceCheck = true;
            }
        }
    }

    /// <summary>Maps widget instances and active ViewModels by hierarchy path for XML and compiled trees.</summary>
    private static Dictionary<string, (Widget Widget, object? ViewModel)>[] Identities(Run3 run) =>
        [.. run.Movies.Take(2).Select(x => IdentitiesOf(x?.RootWidget))];

    private static readonly FieldInfo? ViewModelOfView = typeof(GauntletView).GetField("_viewModel", BindingFlags.Instance | BindingFlags.NonPublic);

    private static Dictionary<string, (Widget Widget, object? ViewModel)> IdentitiesOf(Widget? root)
    {
        var identities = new Dictionary<string, (Widget, object?)>(StringComparer.Ordinal);
        if (root is null)
            return identities;
        var pending = new Stack<(string, Widget)>();
        pending.Push(("root", root));
        while (pending.Count > 0)
        {
            var (path, widget) = pending.Pop();
            identities[path] = (widget, widget.GetComponent<GauntletView>() is { } view ? ViewModelOfView?.GetValue(view) : null);
            for (var i = 0; i < widget.ChildCount; i++)
                pending.Push(($"{path}[{i}]", widget.GetChild(i)));
        }
        return identities;
    }

    /// <summary>
    /// Detects widgets recreated by the interpreted XML engine despite bound list data remaining unchanged.
    /// </summary>
    private static List<Widget> RebuiltInXml(Dictionary<string, (Widget Widget, object? ViewModel)>[] before, Dictionary<string, (Widget Widget, object? ViewModel)>[] after)
    {
        var rebuilt = new List<Widget>();
        // Evaluates shallowest paths first so parent rebuilds encompass descendants.
        var rebuiltPaths = new HashSet<string>(StringComparer.Ordinal);
        foreach (var (path, xmlAfter) in after[0].OrderBy(x => x.Key.Length))
        {
            if (IsUnderAny(path, rebuiltPaths))
                continue;
            if (before[0].TryGetValue(path, out var xmlBefore) && xmlBefore.Widget != xmlAfter.Widget
                && xmlBefore.ViewModel is not null && ReferenceEquals(xmlBefore.ViewModel, xmlAfter.ViewModel)
                && before[1].TryGetValue(path, out var compiledBefore) && after[1].TryGetValue(path, out var compiledAfter)
                && compiledBefore.Widget == compiledAfter.Widget)
            {
                rebuilt.Add(xmlAfter.Widget);
                rebuiltPaths.Add(path);
            }
        }
        return rebuilt;
    }

    /// <summary>Determines whether a hierarchy path represents a descendant of any path in <paramref name="ancestors"/>.</summary>
    private static bool IsUnderAny(string path, HashSet<string> ancestors)
    {
        if (ancestors.Count == 0)
            return false;
        for (var end = path.LastIndexOf('['); end > 0; end = path.LastIndexOf('[', end - 1))
        {
            if (ancestors.Contains(path.Substring(0, end)))
                return true;
        }
        return false;
    }

    /// <summary>
    /// Determines whether replacing a child ViewModel updated the compiled widget while leaving the XML widget unchanged.
    /// </summary>
    private static bool IsStaleInXml(AgreedValues before, string path, Dictionary<string, string> xmlAfter, Dictionary<string, string> compiledAfter)
    {
        if (!before.TryGetValue(path, out var agreed))
            return false;
        foreach (var (key, was) in agreed)
        {
            if (xmlAfter.TryGetValue(key, out var xml) && HashOf(xml) == was
                && compiledAfter.TryGetValue(key, out var compiled) && HashOf(compiled) != was)
            {
                return true;
            }
        }
        return false;
    }

    /// <summary>
    /// Computes 64-bit value hashes for matching widget properties across XML and compiled trees to minimize memory footprint.
    /// </summary>
    private Dictionary<string, ulong> Agreed(Dictionary<string, string> xmlValues, Dictionary<string, string> compiledValues)
    {
        var agreed = new Dictionary<string, ulong>(StringComparer.Ordinal);
        foreach (var (key, xml) in xmlValues)
        {
            if (!WidgetSnapshot.IsField(key) && compiledValues.TryGetValue(key, out var compiled) && compiled == xml)
                agreed[Shared(key)] = HashOf(xml);
        }
        return agreed;
    }

    private readonly Dictionary<string, string> _keys = new(StringComparer.Ordinal);

    /// <summary>Interns snapshot property key strings to deduplicate allocations across widget hierarchy traversals.</summary>
    private string Shared(string key)
    {
        if (_keys.TryGetValue(key, out var shared))
            return shared;
        _keys[key] = key;
        return key;
    }

    /// <summary>Calculates a 64-bit FNV-1a hash of the specified string value.</summary>
    private static ulong HashOf(string value)
    {
        unchecked
        {
            var hash = 14695981039346656037UL;
            foreach (var c in value)
            {
                hash ^= c;
                hash *= 1099511628211UL;
            }
            return hash;
        }
    }

    /// <summary>Extracts the widget hierarchy path from a snapshot property key.</summary>
    private static string WidgetPathOf(string key)
    {
        var end = key.IndexOfAny(['.', ':']);
        return end < 0 ? key : key.Substring(0, end);
    }

    /// <summary>Determines whether a property key corresponds to an intentionally diverged widget or descendant.</summary>
    private static bool IsDiverged(string key, List<string> divergedPaths)
    {
        var widget = WidgetPathOf(key);
        return divergedPaths.Any(x => widget.StartsWith(x, StringComparison.Ordinal) && (widget.Length == x.Length || widget[x.Length] == '['));
    }

    /// <summary>Resolves current hierarchy paths for all diverged XML widgets.</summary>
    private static List<string> DivergedPaths(Run3 run)
    {
        var paths = new List<string>();
        if (run.Movies[0]?.RootWidget is not { } root)
            return paths;
        foreach (var widget in run.Diverged)
        {
            var steps = new List<int>();
            var current = widget;
            while (current != root && current.ParentWidget is { } parent)
            {
                steps.Insert(0, parent.GetChildIndex(current));
                current = parent;
            }
            if (current == root)
                paths.Add("root" + string.Concat(steps.Select(x => $"[{x}]")));
        }
        return paths;
    }

    /// <summary>Navigates the widget hierarchy to find the widget at the specified path, returning <see langword="null"/> if not found.</summary>
    private static Widget? WidgetAt(Widget root, string path)
    {
        var current = root;
        foreach (var part in path.Substring("root".Length).Split(['['], StringSplitOptions.RemoveEmptyEntries))
        {
            var index = int.Parse(part.TrimEnd(']'), System.Globalization.CultureInfo.InvariantCulture);
            if (index >= current.ChildCount)
                return null;
            current = current.GetChild(index);
        }
        return current;
    }

    /// <summary>Captures shallow property agreement maps between XML and compiled widget hierarchies.</summary>
    private AgreedValues Shallow(Run3 run) => run.Timed("snapshots", () =>
    {
        var agreed = new AgreedValues(StringComparer.Ordinal);
        if (run.Movies[0]?.RootWidget is not { } xmlRoot || run.Movies[1]?.RootWidget is not { } compiledRoot)
            return agreed;
        var compiled = WidgetSnapshot.Take(compiledRoot, _compiler.VisibleType, 0);
        foreach (var (path, xmlValues) in WidgetSnapshot.Take(xmlRoot, _compiler.VisibleType, 0))
        {
            if (compiled.TryGetValue(path, out var compiledValues))
                agreed[path] = Agreed(xmlValues, compiledValues);
        }
        return agreed;
    });

    /// <summary>
    /// Verifies state parity across XML, compiled, and control trees, checking snapshots, ViewModel call logs, and assertions.
    /// </summary>
    /// <param name="label">The diagnostic label identifying the active evaluation step.</param>
    /// <param name="deep">Indicates whether to perform deep recursive property inspection.</param>
    /// <param name="replacingBefore">Baseline property values before child ViewModel replacement, used to detect stale bindings.</param>
    /// <param name="trees">Indicates whether to compare widget hierarchies.</param>
    /// <param name="keepShallow">Indicates whether to retain shallow snapshot agreement maps.</param>
    /// <returns>Shallow agreement maps when requested by <paramref name="keepShallow"/>; otherwise, <see langword="null"/>.</returns>
    private AgreedValues? Check(Run3 run, string label, bool deep = false, AgreedValues? replacingBefore = null, bool trees = true, bool keepShallow = false)
    {
        OracleMemoryGuard.At("checking after " + label);
        run.Checks++;
        var intended = run.IntendedSinceCheck;
        run.IntendedSinceCheck = false;

        // Captures pre- and post-replacement state directly during traversal to avoid duplicate tree scans.
        var stale = new List<string>();
        var shallow = keepShallow && !deep ? new AgreedValues(StringComparer.Ordinal) : null;
        if (keepShallow && deep)
            throw new ArgumentException("A deep comparison reads more than a shallow snapshot holds.", nameof(keepShallow));
        Action<string, Dictionary<string, string>, Dictionary<string, string>>? visit = replacingBefore is null && shallow is null ? null : (path, xmlValues, compiledValues) =>
        {
            if (replacingBefore is not null && IsStaleInXml(replacingBefore, path, xmlValues, compiledValues))
                stale.Add(path);
            // Omits paths where widgets do not exist on both sides.
            if (shallow is not null && xmlValues.Count > 0 && compiledValues.Count > 0)
                shallow[path] = Agreed(xmlValues, compiledValues);
        };

        // Compares widgets incrementally during traversal to avoid allocating massive full-tree snapshot dictionaries.
        var roots = run.Movies.Select(x => trees ? x?.RootWidget : null).ToArray();
        var differences = run.Timed(deep ? "compare deep" : "compare", () => WidgetSnapshot.Compare(roots[0], roots[1], roots[2], _compiler.VisibleType, deep ? 2 : 0, missingControlIsUnstable: true, visit));
        if (stale.Count > 0 && run.Movies[0]?.RootWidget is { } xmlRoot)
        {
            run.Diverged.AddRange(stale.Select(x => WidgetAt(xmlRoot, x)).OfType<Widget>());
            intended = true;
        }
        var divergedPaths = DivergedPaths(run);
        foreach (var (key, difference, xml, compiled) in differences)
        {
            // Skips subscriber discrepancies caused by discarded XML list items retaining ancestor subscriptions.
            if (key.EndsWith(WidgetSnapshot.RemovedSubscribers, StringComparison.Ordinal) && WidgetSnapshot.HandlerCount(xml) >= WidgetSnapshot.HandlerCount(compiled))
                continue;
            if (IsRebuildRecord(run, key, xml, compiled))
                continue;
            if (!LoaderOracle.IgnoredProperties.ContainsKey(LoaderOracle.LastSegment(key)) && !IsDiverged(key, divergedPaths) && run.Reported.Add(difference))
                Record(run, $"{label}: {difference}");
        }
        run.RebuiltSinceCheck.Clear();

        // Compares ViewModel invocation logs for the current step, skipping checks when an intentional deviation occurred.
        var steps = run.Timed("logs", () => run.Logs.Select((x, side) => x.Entries.Skip(run.LogMarks[side]).ToList()).ToArray());
        // Filters out reset write-backs emitted by XML during widget disconnection.
        if (!intended && steps[0].SequenceEqual(steps[2]) && !steps[0].SequenceEqual(steps[1])
            && steps[0].Where(x => !IsResetWrittenBack(run, x)).SequenceEqual(steps[1]))
        {
            intended = true;
        }
        if (!intended && steps[0].SequenceEqual(steps[2]))
        {
            for (var i = 0; i < Math.Max(steps[0].Count, steps[1].Count); i++)
            {
                var xmlEntry = i < steps[0].Count ? steps[0][i] : "<nothing>";
                var compiledEntry = i < steps[1].Count ? steps[1][i] : "<nothing>";
                if (xmlEntry != compiledEntry)
                {
                    if (Environment.GetEnvironmentVariable("UIEXTENDEREX_ORACLE_DUMP_LOGS") == "1")
                    {
                        NUnit.Framework.TestContext.Progress.WriteLine($"--- {label}: this step's calls from {Math.Max(0, i - 6)}");
                        foreach (var entry in steps[0].Skip(Math.Max(0, i - 6)).Take(12))
                            NUnit.Framework.TestContext.Progress.WriteLine("  X " + entry);
                        foreach (var entry in steps[1].Skip(Math.Max(0, i - 6)).Take(12))
                            NUnit.Framework.TestContext.Progress.WriteLine("  C " + entry);
                    }
                    Record(run, $"{label}: call {i} of the step: XML '{xmlEntry}', compiled '{compiledEntry}'");
                    break;
                }
            }
        }
        for (var side = 0; side < 3; side++)
            run.LogMarks[side] = run.Logs[side].Entries.Count;

        var asserts = run.Asserts.Select(x => x.Count - run.ComparedAsserts).ToArray();
        if (asserts[0] == asserts[2] && asserts[0] != asserts[1])
            Record(run, $"{label}: asserts XML {asserts[0]}, compiled {asserts[1]} [{string.Join(" | ", run.Asserts[0].Skip(run.ComparedAsserts).Take(2))}] [{string.Join(" | ", run.Asserts[1].Skip(run.ComparedAsserts).Take(2))}]");
        else if (asserts[0] == asserts[1])
        {
            // Compares assertion frequency and diagnostic message parity against the control baseline.
            var stepAsserts = run.Asserts.Select(x => x.Skip(run.ComparedAsserts).ToList()).ToArray();
            foreach (var difference in LoaderOracle.AssertDifferences(stepAsserts[0], [.. stepAsserts[1].Select(run.CompiledAsVisible)], stepAsserts[2]).Take(3))
                Record(run, $"{label}: {difference}");
        }
        // Synchronizes assertion collections across all three variants using unified padding.
        foreach (var list in run.Asserts)
        {
            if (list.Count < run.Asserts.Max(x => x.Count))
                list.AddRange(Enumerable.Repeat("<padding>", run.Asserts.Max(x => x.Count) - list.Count));
        }
        run.ComparedAsserts = run.Asserts[0].Count;
        return shallow;
    }

    /// <summary>Formats diagnostic hierarchy dumps of GauntletView instances and their bound ViewModels.</summary>
    private static string DumpViews(GauntletView view, int depth)
    {
        var flags = BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public;
        var viewModel = typeof(GauntletView).GetField("_viewModel", flags)?.GetValue(view);
        var list = typeof(GauntletView).GetField("_bindingList", flags)?.GetValue(view);
        var children = (IEnumerable) typeof(GauntletView).GetField("_children", flags)!.GetValue(view)!;
        var sb = new System.Text.StringBuilder();
        sb.AppendLine($"{new string(' ', depth * 2)}{view.Target.GetType().Name} path={view.ViewModelPathString} vm={viewModel?.GetType().Name ?? "null"} list={list?.GetType().Name ?? "null"}");
        foreach (GauntletView child in children)
            sb.Append(DumpViews(child, depth + 1));
        return sb.ToString();
    }

    // --- the steps ------------------------------------------------------------------------------------------------------

    /// <summary>Traverses matching ViewModel instances across all three graphs in lockstep, yielding their hierarchical paths.</summary>
    private static IEnumerable<(string Path, ViewModel?[] Instances)> ViewModelsOf(Run3 run)
    {
        var pending = new Queue<(string, ViewModel?[])>();
        pending.Enqueue(("Root", run.ViewModels.Cast<ViewModel?>().ToArray()));
        var visited = new HashSet<ViewModel>();
        while (pending.Count > 0)
        {
            var (path, instances) = pending.Dequeue();
            if (instances[0] is not { } first || !visited.Add(first))
                continue;
            yield return (path, instances);

            foreach (var property in BoundProperties(first.GetType()))
            {
                if (typeof(ViewModel).IsAssignableFrom(property.PropertyType))
                {
                    pending.Enqueue(($"{path}\\{property.Name}", instances.Select(x => x is null ? null : (ViewModel?) property.GetValue(x)).ToArray()));
                }
                else if (typeof(IMBBindingList).IsAssignableFrom(property.PropertyType))
                {
                    var lists = instances.Select(x => x is null ? null : property.GetValue(x) as IList).ToArray();
                    var count = lists.Min(x => x?.Count ?? 0);
                    for (var i = 0; i < count; i++)
                        pending.Enqueue(($"{path}\\{property.Name}\\{i}", lists.Select(x => x![i] as ViewModel).ToArray()));
                }
            }
        }
    }

    private static readonly System.Collections.Concurrent.ConcurrentDictionary<Type, PropertyInfo[]> BoundPropertiesOf = new();

    /// <summary>Discovers and caches properties decorated with <see cref="DataSourceProperty"/> on the specified type.</summary>
    private static PropertyInfo[] BoundProperties(Type type) => BoundPropertiesOf.GetOrAdd(type, x =>
        [.. x.GetProperties(BindingFlags.Instance | BindingFlags.Public).Where(p => p.IsDefined(typeof(DataSourceProperty)) && p.GetSetMethod() is not null)]);

    private static readonly System.Collections.Concurrent.ConcurrentDictionary<PropertyInfo, Type> ValueTypes = new();

    private static Type ValueTypeOf(PropertyInfo property) => ValueTypes.GetOrAdd(property, SynthValues.ValueTypeOf);

    private static int SeedOf(ViewModel viewModel) => (int) viewModel.GetType().GetField("Seed")!.GetValue(viewModel)!;

    private static bool IsScalar(PropertyInfo property) =>
        !typeof(ViewModel).IsAssignableFrom(property.PropertyType) && !typeof(IMBBindingList).IsAssignableFrom(property.PropertyType);

    private void ChangeProperties(Run3 run)
    {
        for (var round = 1; round <= 2; round++)
        {
            var changed = 0;
            foreach (var (path, instances) in ViewModelsOf(run).ToList())
            {
                var scalars = BoundProperties(instances[0]!.GetType()).Where(IsScalar).ToList();
                if (scalars.Count == 0)
                    continue;
                var seed = SeedOf(instances[0]!);
                foreach (var property in scalars)
                {
                    var value = SynthValues.Get(ValueTypeOf(property), seed, property.Name, round);
                    ApplyToAll(run, $"round {round}: {path}.{property.Name}", side => property.SetValue(instances[side], value));
                }
                if (changed++ < MaxDetailedChecks)
                    Check(run, $"round {round}: {path}");
            }
            Check(run, $"round {round}", deep: true);
        }
    }

    private void ReplaceChildren(Run3 run)
    {
        var seed = 1000;
        var replaced = 0;
        // Captures pre-replacement state to distinguish stale XML views from unintended deviations.
        var phaseBefore = Shallow(run);
        LogMemory("children: after the phase's shallow snapshots");
        // Chains baseline states sequentially across initial detailed replacement steps.
        var before = phaseBefore;
        // Reuses post-replacement widget identities as pre-replacement baselines for subsequent steps.
        Dictionary<string, (Widget Widget, object? ViewModel)>[]? widgetsBefore = null;
        foreach (var (path, instances) in ViewModelsOf(run).ToList())
        {
            foreach (var property in BoundProperties(instances[0]!.GetType()).Where(x => typeof(ViewModel).IsAssignableFrom(x.PropertyType)))
            {
                var childSeed = seed++;
                var detailed = replaced++ < MaxDetailedChecks;
                widgetsBefore ??= run.Timed("identities", () => Identities(run));
                ApplyToAll(run, $"replacing {path}\\{property.Name}", side => property.SetValue(instances[side],
                    Activator.CreateInstance(property.PropertyType, run.Logs[side], $"{path}\\{property.Name}", childSeed)));
                var widgetsAfter = run.Timed("identities", () => Identities(run));
                if (run.Timed("rebuilt", () => RebuiltInXml(widgetsBefore, widgetsAfter)) is { Count: > 0 } rebuilt)
                {
                    run.Diverged.AddRange(rebuilt);
                    run.RebuiltSinceCheck.AddRange(rebuilt);
                    run.IntendedSinceCheck = true;
                }
                widgetsBefore = widgetsAfter;
                if (detailed)
                {
                    before = Check(run, $"replacing {path}\\{property.Name}", replacingBefore: before, keepShallow: replaced < MaxDetailedChecks)!;
                    widgetsBefore = null;
                    if (replaced == 1)
                        LogMemory("children: after the first replacement's check, which keeps its shallow snapshots");
                }
            }
        }
        Check(run, "replacing child ViewModels", deep: true, replacingBefore: phaseBefore);
    }

    /// <summary>
    /// Releases movie instances and verifies that event handlers detach cleanly without leaving lingering subscriptions.
    /// </summary>
    private void Release(Run3 run)
    {
        run.Timed("of which releasing", () => ApplyToAll(run, "releasing the movie", side => run.Movies[side]!.Release()));
        Check(run, "releasing the movie", trees: false);

        var handlers = new Dictionary<string, int>[3];
        for (var side = 0; side < 3; side++)
            handlers[side] = run.Timed("handlers", () => HandlersOf(ViewModelsOf(run).Select(x => (x.Path, x.Instances[side]))));
        foreach (var key in handlers[0].Keys.Union(handlers[1].Keys).OrderBy(x => x, StringComparer.Ordinal))
        {
            var xml = handlers[0].TryGetValue(key, out var x) ? x : 0;
            var compiled = handlers[1].TryGetValue(key, out var c) ? c : 0;
            var control = handlers[2].TryGetValue(key, out var k) ? k : 0;
            if (xml == control && xml != compiled)
                Record(run, $"after release: {key}: XML {xml} handlers, compiled {compiled}");
        }

        foreach (var (path, instances) in ViewModelsOf(run).ToList())
        {
            var seed = SeedOf(instances[0]!);
            foreach (var property in BoundProperties(instances[0]!.GetType()).Where(IsScalar))
            {
                var value = SynthValues.Get(ValueTypeOf(property), seed, property.Name, 3);
                ApplyToAll(run, $"after release: {path}.{property.Name}", side => property.SetValue(instances[side], value));
            }
        }
        Check(run, "changing the ViewModels after release", trees: false);
    }

    /// <summary>Determines whether a ViewModel invocation represents an engine property reset upon widget disconnection.</summary>
    private static bool IsResetWrittenBack(Run3 run, string entry)
    {
        var equals = entry.IndexOf(" = ", StringComparison.Ordinal);
        if (equals < 0)
            return false;
        var target = entry.Substring(0, equals);
        var name = target.Substring(target.LastIndexOf('.') + 1);
        return run.ResetOnRemoval.TryGetValue(name, out var values) && values.Contains(entry.Substring(equals + 3));
    }

    /// <summary>Counts active event handler delegates across all ViewModels and binding lists in the hierarchy.</summary>
    public static Dictionary<string, int> HandlersOf(IEnumerable<(string Path, ViewModel? ViewModel)> viewModels)
    {
        var counts = new Dictionary<string, int>(StringComparer.Ordinal);
        foreach (var (path, viewModel) in viewModels)
        {
            if (viewModel is null)
                continue;
            AddHandlers(counts, path, viewModel);
            foreach (var list in BoundProperties(viewModel.GetType()).Where(x => typeof(IMBBindingList).IsAssignableFrom(x.PropertyType)))
            {
                if (list.GetValue(viewModel) is { } value)
                    AddHandlers(counts, $"{path}\\{list.Name}", value);
            }
        }
        return counts;
    }

    private static void AddHandlers(Dictionary<string, int> counts, string path, object target)
    {
        for (var type = target.GetType(); type is not null && type != typeof(object); type = type.BaseType)
        {
            // Inspects event delegates and handler collections, such as MBBindingList.ListChanged.
            foreach (var field in type.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.DeclaredOnly)
                         .Where(x => typeof(Delegate).IsAssignableFrom(x.FieldType) || IsDelegateList(x.FieldType)))
            {
                var handlers = field.GetValue(target) switch
                {
                    Delegate single => single.GetInvocationList().Length,
                    ICollection list => list.Count,
                    _ => 0,
                };
                if (handlers > 0)
                    counts[$"{path}.{field.Name}"] = handlers;
            }
        }
    }

    private static bool IsDelegateList(Type type) =>
        typeof(ICollection).IsAssignableFrom(type) && type.IsGenericType && type.GetGenericArguments() is { Length: 1 } items && typeof(Delegate).IsAssignableFrom(items[0]);

    private const int MaxDetailedLists = 3;

    private void ChangeLists(Run3 run)
    {
        var seed = 2000;
        var lists = 0;
        foreach (var (path, instances) in ViewModelsOf(run).ToList())
        {
            foreach (var property in BoundProperties(instances[0]!.GetType()).Where(x => typeof(IMBBindingList).IsAssignableFrom(x.PropertyType)))
            {
                var itemType = property.PropertyType.GetGenericArguments()[0];
                var listPath = $"{path}\\{property.Name}";
                IList ListOf(int side) => (IList) property.GetValue(instances[side])!;
                object NewItem(int side, int itemSeed) => Activator.CreateInstance(itemType, run.Logs[side], $"{listPath}\\new{itemSeed}", itemSeed)!;

                // Executes detailed checks on initial lists, batching subsequent list checks for efficiency.
                var detailed = lists++ < MaxDetailedLists;
                void CheckIfDetailed(string step)
                {
                    if (detailed)
                        Check(run, $"{listPath}: {step}");
                }

                var added = seed++;
                ApplyToAll(run, $"{listPath}: add", side => ListOf(side).Add(NewItem(side, added)));
                MarkStaleIndexed(run);
                CheckIfDetailed("add");
                var inserted = seed++;
                ApplyToAll(run, $"{listPath}: insert at 0", side => ListOf(side).Insert(0, NewItem(side, inserted)));
                MarkStaleIndexed(run);
                CheckIfDetailed("insert at 0");
                ApplyToAll(run, $"{listPath}: remove at 0", side => ListOf(side).RemoveAt(0));
                MarkStaleIndexed(run);
                CheckIfDetailed("remove at 0");
                ApplyToAll(run, $"{listPath}: clear", side => ListOf(side).Clear());
                MarkStaleIndexed(run);
                CheckIfDetailed("clear");
                var refilled = seed++;
                ApplyToAll(run, $"{listPath}: add after clear", side => ListOf(side).Add(NewItem(side, refilled)));
                MarkStaleIndexed(run);
                if (!detailed)
                    Check(run, $"{listPath}: add, insert, remove, clear, add");
                else
                    CheckIfDetailed("add after clear");
            }
        }
    }

    private static readonly MethodInfo EventFired = typeof(Widget).GetMethod("EventFired", BindingFlags.Instance | BindingFlags.NonPublic)
        ?? throw new InvalidOperationException("Widget.EventFired is gone.");

    /// <summary>
    /// Triggers widget command events across all paired widgets with varying parameter sets, verifying execution parity.
    /// </summary>
    private void FireCommands(Run3 run, HashSet<string> eventNames)
    {
        if (eventNames.Count == 0)
            return;
        var trees = run.Movies.Select(x => x?.RootWidget).ToArray();
        if (trees.Any(x => x is null))
            return;
        foreach (var (path, widgets) in PairedWidgets(trees!))
        {
            // Invokes commands only when at least one variant attaches event listeners.
            if (!widgets.Any(HasEventListeners))
                continue;
            foreach (var eventName in eventNames.OrderBy(x => x, StringComparer.Ordinal))
            {
                foreach (var (argumentsLabel, arguments) in new (string, Func<Widget, object[]>)[] { ("()", _ => []), ("(widget)", w => [w]), ("(\"7\")", _ => ["7"]) })
                    ApplyToAll(run, $"{path} {eventName}{argumentsLabel}", side => EventFired.Invoke(widgets[side], [eventName, arguments(widgets[side])]));
            }
        }
        Check(run, "firing commands", deep: true);
    }

    private static readonly FieldInfo? EventFireField = typeof(Widget).GetField("EventFire", BindingFlags.Instance | BindingFlags.NonPublic);

    private static bool HasEventListeners(Widget widget) => EventFireField is null || EventFireField.GetValue(widget) is not null;

    private static IEnumerable<(string Path, Widget[] Widgets)> PairedWidgets(Widget[] roots)
    {
        var pending = new Stack<(string, Widget[])>();
        pending.Push(("root", roots));
        while (pending.Count > 0)
        {
            var (path, widgets) = pending.Pop();
            yield return (path, widgets);
            var count = widgets[0].ChildCount;
            if (widgets.Any(x => x.ChildCount != count))
                continue;
            for (var i = count - 1; i >= 0; i--)
                pending.Push(($"{path}[{i}]", widgets.Select(x => x.GetChild(i)).ToArray()));
        }
    }
}