using Bannerlord.UIExtenderEx.GauntletUI.CodeGenerator;

using HarmonyLib;
using HarmonyLib.BUTR.Extensions;

using NUnit.Framework;

using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text.RegularExpressions;

using TaleWorlds.GauntletUI.Data;
using TaleWorlds.GauntletUI.PrefabSystem;
using TaleWorlds.Library;

namespace Bannerlord.UIExtenderEx.Tests.CompiledPrefabs;

/// <summary>
/// Compares code generator output against TaleWorlds GauntletUI code generator output when mixins are absent,
/// accounting for intentional deviations where the game generator diverges from XML loader semantics.
/// <para>
/// Verifies that compiled code matches game generator output with specified deviations applied. Requires a full game
/// installation via <c>BANNERLORD_GAME_DIR</c>, <c>BANNERLORD_STABLE_DIR</c>, or default Steam installation path.
/// </para>
/// </summary>
[NonParallelizable]
public class GameGeneratorEquivalenceTests
{
    private const string Namespace = "Bannerlord.UIExtenderEx.AutoGenerated";

    /// <summary>
    /// Defines regex transformations representing intentional deviations from TaleWorlds code generation output.
    /// Applied to game generator output prior to comparison.
    /// </summary>
    private static readonly (string Pattern, string Replacement, string Reason)[] IntendedDeviations =
    [
        (
            @"(?m)^using (?:System\.Numerics|TaleWorlds\.Library);\n",
            "",
            "Generated files import no namespace and write every name out in full. An imported namespace is open to any " +
            "assembly that puts a type or an extension method into it, and binding would then depend on assemblies no build " +
            "records as a dependency (PrefabDependencies)."
        ),
        (
            @"System\.String propertyName, (?<type>Vec2|Color) e\)",
            "System.String propertyName, TaleWorlds.Library.${type} e)",
            "The widget notification payloads the game names through 'using TaleWorlds.Library', written out in full."
        ),
        (
            @"System\.String propertyName, Vector2 e\)",
            "System.String propertyName, System.Numerics.Vector2 e)",
            "The same for System.Numerics.Vector2."
        ),
        (
            @" :\s*TaleWorlds\.GauntletUI\.PrefabSystem\.IGeneratedUIPrefabCreator",
            "",
            "The entry point class implements no interface of the game's. GeneratedPrefabContext.CollectPrefabs instantiates " +
            "every IGeneratedUIPrefabCreator in every loaded assembly and registers what it collects, so implementing it " +
            "would let cached builds this session never validated register themselves. CompiledPrefabManager binds the " +
            "method by name and registers only what its fingerprint still fits."
        ),
        (
            @"\n\t+_datasource_\w+\.\w+ = [\w.]+\.(?:Name|ToString\(\));",
            "",
            "Writing a widget value back to a ViewModel: ViewModel.SetPropertyValue invokes the setter with the value as " +
            "it stands and converts nothing, so a Sprite going into a string property never lands. The game's generator " +
            "converts it with .Name (and a Color with .ToString()), writing back something the loader never writes."
        ),
        (
            @"\n(?<indent>\t+)if \((?<source>[\w.]+) != null\)\n\k<indent>\{\n\k<indent>\t(?<target>[\w.]+) = this\.Context\.(?<call>SpriteData\.GetSprite|BrushFactory\.GetBrush)\(\k<source>\);\n\k<indent>\}",
            "\n${indent}if (${source} != null)\n${indent}{\n${indent}\t${target} = this.Context.${call}(${source});\n" +
            "${indent}}\n${indent}else\n${indent}{\n${indent}\t${target} = null;\n${indent}}",
            "A null string reaching a Sprite or Brush property: WidgetExtensions.ConvertObject only converts a non-null " +
            "string and hands the null straight to the setter, so the loader clears the property. The game's generator " +
            "guards the whole assignment and leaves whatever was there before."
        ),
        (
            @"//Found widget (?:partial path )?during generation - (?<value>[^\n]*)\n(?<indent>\t*)(?<target>[\w.]+)\.(?<property>\w+) = [^\n]*;",
            "//Widget found by path when the attributes are set - ${value}\n${indent}" + WidgetReferenceCall,
            "An attribute naming another widget: SetWidgetAttributeFromString runs FindChild from the widget over the tree " +
            "as it stands when the attributes are set, and assigns inside its try/catch. The game's generator walks the " +
            "template instead, which is not the tree the loader walks - a child in a prefab's logical children location is " +
            "not a child of the widget that declares it, a prefab's own widgets can carry the same Id - and assigns null " +
            "where the loader leaves a widget of the wrong type unassigned. The fork emits the loader's call."
        ),
        (
            @"(?<indent>\n\t*)(?<target>[\w.]+)\.(?<property>\w+) = \k<target>\.FindChild\(new TaleWorlds\.Library\.BindingPath\(@""(?<value>[^""]*)""\)\) as [\w.]+;",
            "${indent}//Widget found by path when the attributes are set - ${value}${indent}" + WidgetReferenceCall,
            "The same, for a reference the game's generator could not resolve at all and left to FindChild at runtime."
        ),
    ];

    private const string WidgetReferenceCall =
        "TaleWorlds.GauntletUI.PrefabSystem.WidgetExtensions.SetWidgetAttributeFromString(${target}, @\"${property}\", @\"${value}\", " +
        "${target}.Context.BrushFactory, ${target}.Context.SpriteData, null, null, null, null, null);";

    /// <summary>
    /// Defines code constructs that differ substantially in structure between generators and are stripped from both
    /// outputs to permit exact comparisons of surrounding logic.
    /// </summary>
    private static readonly (string Pattern, string Reason)[] IgnoredConstructs =
    [
        (
            @"\n\t+[\w.]+\.EventFire [+-]= EventListenerOf\w+;",
            "Where a widget's command listener is taken off and put back. GauntletView.RefreshBinding takes the handlers of " +
            "the view and every view below it off before it writes the values, and attaches the EventFire one after, whatever " +
            "data source the view found; OnCommand resolves the owner from the movie's root, so a widget whose own scope is " +
            "null still runs a command on the scope above. The fork takes the listeners of a scope's subtree off as its " +
            "refresh starts and attaches each after its widget's values, for a null scope too; the game's generator attaches " +
            "them in the refresh of a scope that is not null only. FuzzFindingTests.ACommand_OfAWidgetWhoseScopeIsNull, " +
            "AnEventFiredWhileTheValuesAreWritten_RunsNoCommand and AWidgetsOwnHandler_RunsBeforeTheCommand pin it against XML."
        ),
        (
            @"\n(?<i>\t+)if \(_\w+ == null\)\n\k<i>\{\n(?:\k<i>\t+(?:if \(_\w+ == null\)|\{|\}|[\w.]+\.SetDataSource\(null\);)\n)*?\k<i>\}",
            "A scope handed null: GauntletView.RefreshBindingWithChildren refreshes every view below whatever data source it " +
            "found, so the fork attaches the command listeners there (the construct above, already gone by now) and hands " +
            "null on to the prefabs bound below. The game's generator does nothing for a null scope. " +
            "FuzzFindingTests.ACommand_OfAWidgetWhoseScopeIsNull pins it against XML."
        ),
        (
            @"\n(?<i>\t+)for \(var i = 0; i < _datasource_\w+\.Count; i\+\+\)\n\k<i>\{\n(?:[^\n]*\n)*?\k<i>\}",
            "Filling a bound list, and adding to one (below): the fork builds each item through GauntletView.AddItemToList's " +
            "own steps, and fills a list on binding the way the loader does, one AddItemToList per item in order. The " +
            "template follows from how many items the list already holds - so a list of one takes the default template, " +
            "not the last-item one - and appending under a last-item template rebuilds the previous last item with the " +
            "default template, whichever built it: instantiated as the last child, the old item removed from in front of " +
            "it, moved to its place and bound, then it and the new last item moved with force, which fires " +
            "SiblingIndexChanged on each. An item is instantiated as the list's last child and moved to its index only once " +
            "its attributes are set. The game's generator picks each template from the list's final length, keeps a " +
            "first-item template the loader replaces, and inserts at the index first. FuzzFindingTests pins it against XML."
        ),
        (
            @"\n(?<i>\t+)case TaleWorlds\.Library\.ListChangedType\.ItemAdded:\n\k<i>\{\n(?:[^\n]*\n)*?\k<i>\}",
            "The same, for an item added to the list afterwards."
        ),
        (
            // Anchor closing brace to the opening indentation to avoid terminating on nested blocks.
            @"\n(?<i>\t+)//Requires data component\n\k<i>\{\n(?:[^\n]*\n)*?\k<i>\}",
            "The fork puts a GeneratedWidgetData on every widget, because GauntletView.ConvertCommandParameter can answer " +
            "'what is the data source behind this widget' for any widget at all. The game's generator puts one only on drag " +
            "targets and list items, and hands a command null for anything else."
        ),
        (
            // Match comments positioned one indentation level inside the braces.
            @"\n(?<i>\t+)\{\n\k<i>\t//Requires component data (?:assignment|to be cleared)\n(?:[^\n]*\n)*?\k<i>\}",
            "Same reason: the fork keeps that component's Data up to date for every widget, not only for the few the game's " +
            "generator attaches one to."
        ),
        (
            @"\n\t+[\w.]+\.Id = """";",
            "An empty Id. WidgetTemplate.CreateWidgets sets widget.Id = Id on every widget, and a template without an Id " +
            "has \"\" for one, so a prefab used without an Id of its own loses the Id its root declared. The fork writes " +
            "that assignment wherever the loader makes it; the game's generator writes only the Ids that are there."
        ),
        (
            @"\n(?<i>\t+)private System\.Boolean HandleViewModelPropertyChangeWith\w*ValueOf_\w+\(System\.String propertyName, [\w.]+ value\)\n\k<i>\{\n(?:[^\n]*\n)*?\k<i>\}(?:\n[\t ]*(?=\n))?",
            "The handlers that take a notification's payload. GauntletView.OnPropertyChanged assigns the value a " +
            "PropertyChangedWithValue event carries to every binding of the name and rereads nothing; the game's generator " +
            "rereads the property, which differs as soon as the getter does not return what was announced. The fork " +
            "assigns the payload as the loader does. UnresolvedScalarBindingTests pins it."
        ),
        (
            @"\n(?<i>\t+)if \(HandleViewModelPropertyChangeWith\w*ValueOf_\w+\(e\.PropertyName, e\.Value\)\)\n\k<i>\{\n\k<i>\treturn;\n\k<i>\}",
            "Where those handlers are called from."
        ),
        (
            @"\n\t*//Data: (?:IgnoresRootDataSource|RootDataSource|OverriddenCommands) - [^\n]*",
            "The data the fork tells a dependent prefab's class that the game's generator has no word for: that the view at " +
            "its root is bound where the movie or a list puts it, the DataSource the widget using it gives that view, and the " +
            "commands that widget replaces. Each class header lists its data as a comment."
        ),
        (
            @"\n(?<i>\t+)if \(value == null\)\n\k<i>\{\n(?:\k<i>\t[^\n]*\n)*\k<i>\}",
            "A widget value of a type the ViewModel property cannot take, written back when it is null. The game's generator " +
            "writes nothing for such a pair; ViewModel.SetPropertyValue hands the property the null all the same - a brush " +
            "the name did not find, written back into the string that named it."
        ),
        (
            @"\n\t+[\w.]+\.(?<variant>bool|float|Vec2|Vector2|double|int|uint|Color|)PropertyChanged [+-]= \k<variant>PropertyChangedListenerOf_widget\w*;",
            "Which of a widget's change notifications its writeback listens to. The game's generator subscribes to all nine on " +
            "every bound widget, as the loader's view does. The fork reads the widget class's IL for the notifications it can " +
            "raise under a property it binds, and subscribes to those (WidgetRaises): the view writes back only a bound name, " +
            "so a notification never raised under one is one it does nothing with. All nine where the IL does not decide it. " +
            "WidgetRaisesTests pins the reading, and the binding oracle the writebacks against XML."
        ),
        (
            @"\n[\t ]*\n(?<i>\t+)private void (?:bool|float|Vec2|Vector2|double|int|uint|Color)?PropertyChangedListenerOf_widget\w*\([^\n]*\)\n\k<i>\{\n[^\n]*\n\k<i>\}",
            "The listeners of those notifications, one per notification subscribed to."
        ),
        (
            @"\n\t+private static [^\n]*_uiExtenderEx\w+;",
            "The fields behind the resource-constant resolver; see ResourceConstant below."
        ),
        (
            @"\n(?<i>\t+)private static void UIExtenderEx_EnsureConstantDefinitions\(\)\n\k<i>\{\n(?:[^\n]*\n)*?\k<i>\}(?:\n[\t ]*(?=\n))?",
            "The reconstructed constant definitions and parameter values; see ResourceConstant below."
        ),
        (
            @"\n(?<i>\t+)private string UIExtenderEx_ResolveResourceValue\(string value\)\n\k<i>\{\n(?:[^\n]*\n)*?\k<i>\}(?:\n[\t ]*(?=\n))?",
            "The resolver itself; see ResourceConstant below."
        ),
    ];

    /// <summary>
    /// Matches runtime resource constants resolving sprite or brush-layer dimensions. Replaces both runtime-resolved
    /// blocks and game generator baked constants with a normalized marker for structural comparison.
    /// </summary>
    /// <summary>Matches the resolve comment and following assignment block anchored to comment indentation.</summary>
    private static readonly Regex ForkResolvedConstant = new(
        @"//From constant (?<name>[^\n]+), resolved against the widget's own resources\n(?<i>\t*)\{\n(?<body>(?:[^\n]*\n)*?)\k<i>\}");

    /// <summary>Matches the specific assignment statement within a resolved constant block.</summary>
    private static readonly Regex ForkResolvedAssignment = new(@"(?<target>[\w.]+) = [^\n]*uiExtenderExResourceValue[^\n]*");

    private static string ResolvedConstantMarker(string name, string indent, string target) =>
        $"//Resource constant {name}\n{indent}{target} = <resolved at runtime>;";

    /// <summary>
    /// Folds runtime-resolved constants in <paramref name="forkOutput"/> and corresponding baked constants in
    /// <paramref name="gameOutput"/> into unified markers to verify property targeting equivalence.
    /// </summary>
    private static (string Game, string Fork) FoldResourceConstants(string gameOutput, string forkOutput)
    {
        var names = new List<string>();
        forkOutput = ForkResolvedConstant.Replace(forkOutput, match =>
        {
            var name = match.Groups["name"].Value;
            names.Add(name);
            return ResolvedConstantMarker(name, match.Groups["i"].Value, ForkResolvedAssignment.Match(match.Groups["body"].Value).Groups["target"].Value);
        });
        foreach (var name in names.Distinct())
        {
            var baked = new Regex(@"//From constant " + Regex.Escape(name) + @":[^\n]*\n(?<i>\t*)(?<target>[\w.]+) = [^\n]*");
            gameOutput = baked.Replace(gameOutput, m => ResolvedConstantMarker(name, m.Groups["i"].Value, m.Groups["target"].Value));
        }
        return (gameOutput, forkOutput);
    }

    private static string ApplyIntendedDeviations(string gameOutput)
    {
        foreach (var (pattern, replacement, _) in IntendedDeviations)
            gameOutput = Regex.Replace(gameOutput, pattern, replacement);
        return gameOutput;
    }

    /// <summary>
    /// Defines blocks emitted with equivalent functionality but distinct syntax by both generators, collapsing them
    /// to canonical markers for structural comparison.
    /// </summary>
    private static readonly (string Pattern, string Replacement, string Reason)[] FoldedConstructs =
    [
        (
            @"\n(?<i>\t+)if \(commandName == ""(?<command>[^""]*)""\)\n\k<i>\{\n(?:[^\n]*\n)*?\k<i>\}",
            "\n${i}<command ${command}>",
            "The body of one command. The fork calls a resolved method on ViewModel.ExecuteCommand's terms - as many " +
            "arguments as parameters or nothing runs, a string converted as ConvertValueTo converts it, an argument of the " +
            "wrong type skipping the call, what the method throws wrapped as reflection wraps it - and prepares the " +
            "arguments as GauntletView.OnCommand does. The game's generator indexes args by the method's parameters and " +
            "casts each one. CommandLoaderParityTests pins the fork's behaviour against ExecuteCommand itself."
        ),
        (
            @"\n(?<i>\t*)try\n\k<i>\{\n\k<i>\t(?<statement>[^\n]*)\n\k<i>\}\n\k<i>catch \(System\.Exception(?: uiExtenderExAttributeFailure)?\)\n\k<i>\{\n\k<i>\t[^\n]*\n\k<i>\}",
            "\n${i}${statement}",
            "An attribute assignment inside the loader's try/catch. SetWidgetAttributeFromString catches whatever the " +
            "assignment throws - a setter running into state the widget does not have yet - asserts and moves on to the next " +
            "attribute; the game's generator let it out and the movie never opened. Unwrapped on the fork's side, so the " +
            "assignment itself is still compared with the game's."
        ),
        (
            @"new TaleWorlds\.Library\.Color\([^)]*\)",
            "new TaleWorlds.Library.Color(<channels>)",
            "The channels of a colour. The game's generator writes each with float.ToString(), which on .NET Framework is " +
            "seven digits and not always the same float back: #F3DCB8 came out #F3DCB7. The fork writes the round-trip form. " +
            "Which colour lands where is still compared here; the values are held to the loader's by GamePrefabCorpusTests."
        ),
        (
            // Match unhandled parameter defaults in game generator output.
            @"(?<head>//parameter below has something different then default value type, [^\n]*\n)(?<i>\t*)//\n\k<i>//[^\n]*\n\k<i>//[^\n]*\n\k<i>//[^\n]*\n\k<i>//(?=\n)",
            "${head}${i}<parameter default>",
            "An attribute taking a parameter the enclosing prefab passed as something other than a plain value - a binding, " +
            "typically. WidgetTemplate.SetAttributes assigns the parameter's declared default all the same, and a binding " +
            "replaces it once there is a data source; the game's generator assigns nothing. XmlLoaderParityTests pins it."
        ),
        (
            @"\n(?<i>\t+)if \(value is [^\n]+ uiExtenderExAnnounced_(?<w>_widget(?:_\d+)*)_(?<p>[A-Za-z]\w*)\)\n\k<i>\{\n\k<i>\t(?<target>[^\n]*) = uiExtenderExAnnounced_\k<w>_\k<p>;\n\k<i>\}\n\k<i>else if \(value == null\)\n\k<i>\{\n(?:\k<i>\t[^\n]*\n)*\k<i>\}\n(?:\k<i>else if \(value is System\.String [^\n]+\)\n\k<i>\{\n(?:\k<i>\t[^\n]*\n)*\k<i>\}\n)?\k<i>else\n\k<i>\{\n(?:\k<i>\t[^\n]*\n)*\k<i>\}",
            "\n${i}${target} = ${w}.${p};",
            "A widget value written back to the ViewModel. GauntletView.OnViewPropertyChanged hands SetPropertyValue the value " +
            "the widget announced, which is not always what its property holds by then: NumericUpDownWidget.Value re-enters " +
            "through IntValue and announces the whole number before the value it was given, and an alignment announces its " +
            "name. The game's generator reads the property; the fork assigns the announced value, a name announced for an " +
            "enum parsed back into it (an intended deviation, UIX0025), and anything else of another type through " +
            "SetPropertyValue, as the loader does. Folded to the read, which is the game's line. " +
            "FuzzFindingTests.AWriteBack_TakesTheAnnouncedValue and AnAlignmentBoundToAnEnumProperty pin the behaviour."
        ),
        (
            @"(?<head>HandleWidgetPropertyChangeOf\w+)\((?<args>System\.String propertyName|propertyName), (?:System\.Object value|e)\)",
            "${head}(${args})",
            "The same: the handler takes the announced value along."
        ),
        (
            // Match handled parameter defaults in compiled prefab generator output.
            @"(?<head>//parameter below has something different then default value type, [^\n]*\n)(?<i>\t*)//From parameter [^\n]*(?:\n\k<i>(?!//)[^\n]*;)?",
            "${head}${i}<parameter default>",
            "The same construct as the fork writes it."
        ),
    ];

    private static string FoldConstructs(string output)
    {
        foreach (var (pattern, replacement, _) in FoldedConstructs)
            output = Regex.Replace(output, pattern, replacement);
        return output;
    }

    private static string RemoveIgnoredConstructs(string output)
    {
        // Strip ignored constructs completely rather than marking, as emission locations differ across generators.
        // Verifies exact matching of all surrounding code.
        foreach (var (pattern, _) in IgnoredConstructs)
            output = Regex.Replace(output, pattern, string.Empty);
        return output;
    }

    private static string? _gameDirectory;
    private static readonly List<string> ProbeDirectories = [];
    private static bool _resolverInstalled;
    private static Harmony? _harmony;

    [OneTimeSetUp]
    public void OneTimeSetUp()
    {
        _gameDirectory = FindGameDirectory();
        if (_gameDirectory is null)
            return;

        var gameBin = Path.Combine(_gameDirectory, "bin", "Win64_Shipping_Client");
        ProbeDirectories.Add(gameBin);
        foreach (var module in new[] { "Native", "SandBoxCore", "SandBox", "StoryMode", "CustomBattle" })
        {
            var directory = Path.Combine(_gameDirectory, "Modules", module, "bin", "Win64_Shipping_Client");
            if (Directory.Exists(directory))
                ProbeDirectories.Add(directory);
        }
        if (!_resolverInstalled)
        {
            _resolverInstalled = true;
            AppDomain.CurrentDomain.AssemblyResolve += Resolve;
        }

        // Pre-load widget and ViewModel assemblies required by the generator; core assemblies load from test folder.
        foreach (var file in new[]
        {
            Path.Combine(gameBin, "TaleWorlds.GauntletUI.ExtraWidgets.dll"),
            Path.Combine(gameBin, "TaleWorlds.MountAndBlade.GauntletUI.Widgets.dll"),
            Path.Combine(gameBin, "TaleWorlds.Core.ViewModelCollection.dll"),
            Path.Combine(gameBin, "TaleWorlds.MountAndBlade.ViewModelCollection.dll"),
            Path.Combine(gameBin, "TaleWorlds.CampaignSystem.ViewModelCollection.dll"),
            Path.Combine(_gameDirectory, "Modules", "Native", "bin", "Win64_Shipping_Client", "TaleWorlds.MountAndBlade.GauntletUI.dll"),
            Path.Combine(_gameDirectory, "Modules", "SandBox", "bin", "Win64_Shipping_Client", "SandBox.GauntletUI.dll"),
            Path.Combine(_gameDirectory, "Modules", "SandBox", "bin", "Win64_Shipping_Client", "SandBox.ViewModelCollection.dll"),
        })
        {
            if (!File.Exists(file))
                continue;
            try { Assembly.LoadFrom(file).GetTypes(); }
            catch (ReflectionTypeLoadException) { /* partial load is fine */ }
        }

        // Redirect BasePath.Name to the game folder for resource resolution.
        _harmony = new Harmony(nameof(GameGeneratorEquivalenceTests));
        // Apply prefix with high priority to override competing test fixture patches.
        _harmony.Patch(SymbolExtensions2.GetPropertyGetter(() => BasePath.Name),
            prefix: new HarmonyMethod(typeof(GameGeneratorEquivalenceTests), nameof(BasePathPrefix)) { priority = Priority.First });

        Common.SetInvariantCulture();
        PrefabWorkspace.RefreshWidgetInfo();
    }

    [OneTimeTearDown]
    public void OneTimeTearDown()
    {
        _harmony?.UnpatchAll(nameof(GameGeneratorEquivalenceTests));
    }

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static bool BasePathPrefix(ref string __result)
    {
        __result = _gameDirectory!.Replace('\\', '/') + "/";
        return false;
    }

    private static Assembly? Resolve(object sender, ResolveEventArgs args)
    {
        var name = new AssemblyName(args.Name).Name;
        foreach (var directory in ProbeDirectories)
        {
            var path = Path.Combine(directory, name + ".dll");
            if (File.Exists(path))
                return Assembly.LoadFrom(path);
        }
        return null;
    }

    private static string? FindGameDirectory()
    {
        var candidates = new[]
        {
            Environment.GetEnvironmentVariable("BANNERLORD_GAME_DIR"),
            Environment.GetEnvironmentVariable("BANNERLORD_STABLE_DIR"),
            @"C:\Program Files (x86)\Steam\steamapps\common\Mount & Blade II Bannerlord",
        };
        return candidates.FirstOrDefault(x =>
            !string.IsNullOrEmpty(x) &&
            File.Exists(Path.Combine(x!, "bin", "Win64_Shipping_Client", "TaleWorlds.GauntletUI.CodeGenerator.dll")) &&
            Directory.Exists(Path.Combine(x!, "Modules", "SandBox", "GUI")));
    }

    [TestCase("EscapeMenu", "TaleWorlds.MountAndBlade.ViewModelCollection.EscapeMenu.EscapeMenuVM")]
    [TestCase("RecruitmentPopup", "TaleWorlds.CampaignSystem.ViewModelCollection.GameMenu.Recruitment.RecruitmentVM")]
    public void Fork_EmitsTheSameCodeAsTheGameGenerator(string movieName, string viewModelTypeName)
    {
        if (_gameDirectory is null)
            Assert.Ignore("No game installation found; set BANNERLORD_GAME_DIR to run this test.");

        var viewModelType = AppDomain.CurrentDomain.GetAssemblies().Select(x => x.GetType(viewModelTypeName, false)).FirstOrDefault(x => x is not null);
        if (viewModelType is null)
            Assert.Ignore($"ViewModel type {viewModelTypeName} is not available in this game installation.");

        var gameGenerator = Assembly.LoadFrom(Path.Combine(_gameDirectory!, "bin", "Win64_Shipping_Client", "TaleWorlds.GauntletUI.CodeGenerator.dll"));
        var gameContextType = gameGenerator.GetType("TaleWorlds.GauntletUI.CodeGenerator.UICodeGenerationContext")!;
        var gameVariantType = gameGenerator.GetType("TaleWorlds.GauntletUI.CodeGenerator.UICodeGenerationDatabindingVariantExtension")!;

        var locations = new List<string> { "GUI/GauntletUI/" };
        foreach (var module in new[] { "Native", "SandBoxCore", "SandBox", "StoryMode", "CustomBattle" })
        {
            if (Directory.Exists(Path.Combine(_gameDirectory!, "Modules", module, "GUI")))
                locations.Add($"Modules/{module}/GUI/");
        }
        var data = new Dictionary<string, object> { { "DataSourceType", viewModelType! } };

        // Execute TaleWorlds generator targeting output directory.
        var outputFolder = "UIExtenderExEquivalence_" + movieName;
        var gameContext = Activator.CreateInstance(gameContextType, Namespace, outputFolder)!;
        Invoke(gameContext, gameContextType.GetMethod("Prepare", [typeof(IEnumerable<string>), typeof(IEnumerable<PrefabExtension>)])!, locations, new PrefabExtension[] { new PrefabDatabindingExtension() });
        Invoke(gameContext, gameContextType.GetMethod("AddPrefabVariant")!, movieName, viewModelType!.FullName, Activator.CreateInstance(gameVariantType), data);

        var temp = Path.Combine(Path.GetTempPath(), "UIExtenderEx-equivalence-" + Guid.NewGuid().ToString("N"));
        var workingDirectory = Path.Combine(temp, "a", "b", "c");
        var gameOutput = Path.Combine(temp, "Source", outputFolder);
        Directory.CreateDirectory(workingDirectory);
        Directory.CreateDirectory(gameOutput);
        var previousDirectory = Directory.GetCurrentDirectory();
        Dictionary<string, string> gameFiles;
        try
        {
            Directory.SetCurrentDirectory(workingDirectory);
            Invoke(gameContext, gameContextType.GetMethod("Generate")!);
            gameFiles = Directory.GetFiles(gameOutput, "*.cs").ToDictionary(Path.GetFileName, x => File.ReadAllText(x));
        }
        finally
        {
            Directory.SetCurrentDirectory(previousDirectory);
            try { Directory.Delete(temp, true); } catch (Exception) { /* ignore */ }
        }

        // Execute compiled prefab generator reusing loaded game resources.
        object Property(string name) => gameContextType.GetProperty(name)!.GetValue(gameContext)!;
        var forkContext = new PrefabCodeGenerator(Namespace, (WidgetFactory) Property("WidgetFactory"),
            (TaleWorlds.TwoDimension.SpriteData) Property("SpriteData"), (TaleWorlds.GauntletUI.BrushFactory) Property("BrushFactory"));
        forkContext.AddMovie(movieName, viewModelType.FullName, viewModelType);
        var forkFiles = forkContext.GenerateInMemory().ToDictionary(x => x.Key, x => x.Value);

        Assert.That(forkFiles.Keys, Is.EquivalentTo(gameFiles.Keys));
        foreach (var file in gameFiles)
        {
            var expected = FoldConstructs(RemoveIgnoredConstructs(ApplyIntendedDeviations(Normalize(file.Value))));
            var actual = FoldConstructs(RemoveIgnoredConstructs(Unroot(Normalize(forkFiles[file.Key]))));
            (expected, actual) = FoldResourceConstants(expected, actual);
            expected = DropWritebacksTheForkLeavesOut(expected, actual);
            if (expected != actual)
                Assert.Fail($"{file.Key} differs from the game's generator beyond the deviations this fork makes on purpose. {DumpForDiff(movieName, file.Key, expected, actual)}");
        }
        Assert.That(forkFiles[movieName + ".gen.cs"].Length, Is.GreaterThan(1000), "sanity: the movie produced real code");
    }

    private static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd();

    private static readonly Regex WritebackHandler = new(
        @"\n(?<i>\t+)private void HandleWidgetPropertyChangeOf(?<widget>\w+)\(System\.String propertyName[^\n]*\)\n\k<i>\{\n(?:[^\n]*\n)*?\k<i>\}(?:\n[\t ]*(?=\n))?");

    /// <summary>
    /// Strips writeback handlers for widgets that do not raise property notifications from game generator output,
    /// matching compiled prefab generator suppression behavior.
    /// </summary>
    private static string DropWritebacksTheForkLeavesOut(string gameOutput, string forkOutput)
    {
        var fork = WritebackHandler.Matches(forkOutput).Cast<Match>().Select(x => x.Groups["widget"].Value).ToList();
        var next = 0;
        return WritebackHandler.Replace(gameOutput, match =>
        {
            if (next < fork.Count && fork[next] == match.Groups["widget"].Value)
            {
                next++;
                return match.Value;
            }
            return "";
        });
    }

    /// <summary>
    /// Strips the <c>global::</c> namespace qualification from compiled output to match unrooted game generator output.
    /// </summary>
    private static string Unroot(string forkOutput) => forkOutput.Replace("global::", string.Empty);

    /// <summary>
    /// Writes generator outputs to temporary disk files for diff inspection on test failure.
    /// </summary>
    private static string DumpForDiff(string movieName, string fileName, string expected, string actual)
    {
        try
        {
            var directory = Path.Combine(Path.GetTempPath(), "UIExtenderEx-equivalence-diff", movieName);
            Directory.CreateDirectory(directory);
            File.WriteAllText(Path.Combine(directory, "game-" + fileName), expected);
            File.WriteAllText(Path.Combine(directory, "fork-" + fileName), actual);
            return "Both outputs written to " + directory;
        }
        catch (Exception e)
        {
            return "Could not write the outputs for diffing: " + e.Message;
        }
    }

    // Unwraps TargetInvocationException to rethrow the underlying generator failure.
    private static void Invoke(object target, MethodInfo method, params object?[] arguments)
    {
        try
        {
            method.Invoke(target, arguments);
        }
        catch (TargetInvocationException e) when (e.InnerException is not null)
        {
            throw new InvalidOperationException($"{method.Name} failed: {e.InnerException}", e.InnerException);
        }
    }

}
