name: Test

on:
  repository_dispatch:
    types:
      # If a new version of the game is released, test the repo against it.
      # This way we will always know if the repo is broken on a new update.
      - game_version_update
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'build/**'
  pull_request:
    branches:
      - dev
    # will be triggered when undrafting or requesting review
    types: [review_requested, ready_for_review]
    paths:
      - '.github/workflows/test.yml'
      - 'src/**'
      - 'build/**'

env:
  # Disable the .NET logo in the console output.
  DOTNET_NOLOGO: true
  # Disable the .NET first time experience to skip caching NuGet packages and speed up the build.
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending .NET CLI telemetry to Microsoft.
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: 5.0.x

    - name: Setup BUTR GPR
      uses: actions/setup-dotnet@master
      with:
        source-url: https://nuget.pkg.github.com/BUTR/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Download DepotDownloader_2.3.6
      uses: i3h/download-release-asset@v1
      with:
        owner: SteamRE
        repo: DepotDownloader
        tag: DepotDownloader_2.3.6
        file: depotdownloader-2.3.6.zip

    - name: Extract DepotDownloader_2.3.6
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: depotdownloader-2.3.6.zip
        pathTarget: depotdownloader

    - name: Download Bannerlord binaries
      run: >-
        dotnet depotdownloader/DepotDownloader.dll -app 261550 -depot 261551 -beta ${{secrets.SYNCED_GAME_STABLE_VERSION}} -username ${{secrets.STEAM_LOGIN}}
        -password ${{secrets.STEAM_PASSWORD}} -filelist ./.github/resources/FileFilters.regexp -dir bannerlord
      shell: pwsh

    - name: Download opencover.4.7.922
      uses: i3h/download-release-asset@v1
      with:
        owner: OpenCover
        repo: opencover
        tag: 4.7.922
        file: opencover.4.7.922.zip

    - name: Extract opencover.4.7.922
      uses: DuckSoft/extract-7z-action@v1.0
      with:
        pathSource: opencover.4.7.922.zip
        pathTarget: opencover

    - name: Test Debug
      run: >-
          $game_version=$env:STABLE_VERSION;
          $game_version=$game_version.substring(1);
          dotnet test tests/Bannerlord.UIExtenderEx.Tests/Bannerlord.UIExtenderEx.Tests.csproj --configuration Debug -p:GameVersion=$game_version -p:GameFolder="$PWD/bannerlord";
          dotnet test tests/Bannerlord.UIExtenderEx.Tests/Bannerlord.UIExtenderEx.Tests.csproj --configuration Release -p:GameVersion=$game_version -p:GameFolder="$PWD/bannerlord";
      env:
        STABLE_VERSION: ${{secrets.SYNCED_GAME_STABLE_VERSION}}
      shell: pwsh

    - name: Test Coverage
      run: >-
          opencover/OpenCover.Console.exe -register -target:"dotnet.exe" -targetargs:"test tests/Bannerlord.UIExtenderEx.Tests/Bannerlord.UIExtenderEx.Tests.csproj --configuration Debug --no-build" -filter:"+[Bannerlord.UIExtenderEx*]* -[Bannerlord.UIExtenderEx*.Tests]*" -output:coverage_uiextenderex_debug.xml -mergebyhash;
          opencover/OpenCover.Console.exe -register -target:"dotnet.exe" -targetargs:"test tests/Bannerlord.UIExtenderEx.Tests/Bannerlord.UIExtenderEx.Tests.csproj --configuration Release --no-build" -filter:"+[Bannerlord.UIExtenderEx*]* -[Bannerlord.UIExtenderEx*.Tests]*" -output:coverage_uiextenderex_release.xml -mergebyhash;
      shell: pwsh

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@4.6.1
      with:
        reports: 'coverage_uiextenderex_debug.xml;coverage_uiextenderex_release.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline;Cobertura'
        sourcedirs: './'
        tag: '${{ github.run_number }}_${{ github.run_id }}' # Optional tag or build version.

    - name: Upload ReportGenerator to GitHub
      uses: actions/upload-artifact@v1
      with:
        name: coverage-report
        path: coveragereport

    - name: Upload ReportGenerator to CodeCov
      uses: codecov/codecov-action@v1
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: coveragereport/Cobertura.xml
        fail_ci_if_error: true
